### ISSUE TITLE
GitHub Codespaces failing

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#142]
I am completely clueless. I don't know if this is on me, or on the configuration. Looking for a second set of eyes.

I was attempting to pull up a GitHub Codespaces instance to demonstrate the process for the developer-focused wiki (a "Getting started with GitHub Codespaces" section), and ran into the fact that _I couldn't get it to work!_

The error that kills it is:

```js
write /home/codespace/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: no space left on device
```

<details>
  <summary>Full error log</summary>

```js
=================================================================================
2022-11-29 22:02:58.678Z: Configuration starting...
2022-11-29 22:02:58.720Z: Cloning...
2022-11-29 22:02:58.738Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch main --depth 1 https://github.com/devcontainers-contrib/features "/var/lib/docker/codespacemount/workspace/features"
2022-11-29 22:02:58.744Z: Cloning into '/var/lib/docker/codespacemount/workspace/features'...
2022-11-29 22:02:59.096Z: git process exited with exit code 0
2022-11-29 22:02:59.105Z: $ git -C "/var/lib/docker/codespacemount/workspace/features" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2022-11-29 22:02:59.111Z: git process exited with exit code 0
2022-11-29 22:02:59.451Z: Using image: mcr.microsoft.com/devcontainers/universal:2

2022-11-29 22:05:55.117Z: #11 ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /home/codespace/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: no space left on device
2022-11-29 22:05:55.117Z: 
2022-11-29 22:05:55.117Z: #8 [internal] load metadata for mcr.microsoft.com/devcontainers/universal:linux
2022-11-29 22:05:55.117Z: 
2022-11-29 22:05:55.117Z: ------
2022-11-29 22:05:55.117Z: 
2022-11-29 22:05:55.117Z:  > [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com/devcontainers/universal:linux@sha256:5860442949e556cd1ef53ccfa8d45b0a82d09e78910a46a011aa30a769380102:
2022-11-29 22:05:55.117Z: 
2022-11-29 22:05:55.117Z: ------
2022-11-29 22:05:55.117Z: 
2022-11-29 22:05:55.144Z: ERROR: failed to solve: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /home/codespace/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: no space left on device
2022-11-29 22:05:55.145Z: 
2022-11-29 22:05:55.173Z: Stop (171320 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.23.2-1669759381510 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:linux --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-features-1fd731dbdc54187530bf301a0589adb6-features -f /tmp/devcontainercli-root/container-features/0.23.2-1669759381510/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2022-11-29 22:05:55.173Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.23.2-1669759381510 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:linux --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-features-1fd731dbdc54187530bf301a0589adb6-features -f /tmp/devcontainercli-root/container-features/0.23.2-1669759381510/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2022-11-29 22:05:55.173Z:     at loe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:1339)
2022-11-29 22:05:55.173Z:     at eT (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:1275)
2022-11-29 22:05:55.173Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-11-29 22:05:55.174Z:     at async voe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:2049)
2022-11-29 22:05:55.174Z:     at async Xf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:3212)
2022-11-29 22:05:55.174Z:     at async Jae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:15058)
2022-11-29 22:05:55.174Z:     at async Wae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:14812)
2022-11-29 22:05:55.217Z: Stop (174414 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/features --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/features/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-29 22:05:55.217Z: Exit code 1

====================================== ERROR ====================================
2022-11-29 22:05:55.246Z: Failed to create container.
=================================================================================
2022-11-29 22:05:55.255Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/features --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/features/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-29 22:05:55.267Z: Error Code: 1302

====================================== ERROR ====================================
2022-11-29 22:05:55.300Z: Container creation failed.
=================================================================================
```

</details>

So yeah... I don't think this is a huge problem since I was able to get my own copy (the fork on my personal repo) working just fine. I don't know why it borked when I tried to create one on the main devcontainers-contrib/features proper though.

**Comment by jcbhmr** [comment]
It turns out that I done goofed 🤦‍♂️. When you press "Create a Codespace on main" it uses _your own fork_, not the actual repo that you clicked on! This caused some confusion since _in my own fork_ I was playing around with the devcontainer config (and in the process, broke it), but I falesly attributed it to this repo when I tried to create a Codespace from this repo

![image](https://user-images.githubusercontent.com/61068799/204956339-c555441c-0145-41f1-a66e-14c8f8c699da.png)
![image](https://user-images.githubusercontent.com/61068799/204956325-fff97214-575d-4c92-845a-8432110502d3.png)

☝ That button doesn't create a codespace on devcontainers-contrib/features, it creates on on jcbhmr/devcontainers-contrib-features!

So yeah. This is no longer an issue! 🎉
