### ISSUE TITLE
Ansible feature does not work on arm64 hosts

### ISSUE THREAD

**Issue by SuperMatt** [devcontainers-contrib/features#296]
Hi folks,

I am trying to run my dev container on a Raspberry Pi 4 with the Ansible feature added in, but it is refusing to run with the following error:

```
#0 2.714 /usr/local/bin/featmake: line 146: /usr/local/bin/oras: cannot execute binary file: Exec format error
#0 2.725 ERROR: Feature "Ansible (via pipx)" (ghcr.io/devcontainers-contrib/features/ansible) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/ansible for help troubleshooting this error.
------
Dockerfile.extended:24
--------------------
  23 |     
  24 | >>> RUN cd /tmp/build-features/ansible_1 \
  25 | >>> && chmod +x ./devcontainer-features-install.sh \
  26 | >>> && ./devcontainer-features-install.sh
  27 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp/build-features/ansible_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh" did not complete successfully: exit code: 126
[2023-01-28T11:26:57.796Z] Stop (5215 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-matthew/container-features/0.25.2-1674905210411 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ansible-86f4a91eb81e42e2097f0d7ba3f5b622-features -f /tmp/devcontainercli-matthew/container-features/0.25.2-1674905210411/Dockerfile.extended /tmp/devcontainercli-matthew/empty-folder
[2023-01-28T11:26:56.022Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-matthew/container-features/0.25.2-1674905210411 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ansible-86f4a91eb81e42e2097f0d7ba3f5b622-features -f /tmp/devcontainercli-matthew/container-features/0.25.2-1674905210411/Dockerfile.extended /tmp/devcontainercli-matthew/empty-folder
[2023-01-28T11:26:56.022Z]     at Aoe (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1355)
[2023-01-28T11:26:56.023Z]     at uT (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1291)
[2023-01-28T11:26:56.023Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-28T11:26:56.023Z]     at async Poe (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[2023-01-28T11:26:56.023Z]     at async Zf (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[2023-01-28T11:26:56.023Z]     at async aue (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[2023-01-28T11:26:56.023Z]     at async oue (/home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[2023-01-28T11:26:56.043Z] Stop (8578 ms): Run in Host: /home/matthew/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node /home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/matthew/gits/Ansible --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/matthew/gits/Ansible --log-level debug --log-format json --config /home/matthew/gits/Ansible/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-28T11:26:56.044Z] Exit code 1
[2023-01-28T11:26:56.047Z] Command failed: /home/matthew/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node /home/matthew/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/matthew/gits/Ansible --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/matthew/gits/Ansible --log-level debug --log-format json --config /home/matthew/gits/Ansible/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-28T11:26:56.047Z] Exit code 1
```

My experience with things like this is that it's probably trying to execute an x86_64 binary rather than arm64.

My dev container directive looks like this:

```
{
	"name": "Ubuntu",
	"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers-contrib/features/ansible:2.0.5": {},
		"ghcr.io/eitsupi/devcontainer-features/go-task:1": {}
	},

	"customizations": {
		"vscode": {
			"extensions": [
				"github.copilot",
				"wholroyd.jinja"
			]
		}
	}
}
```

If I comment out the ansible line then then the dev container builds successfully, though this is useless to me because it's Ansible I'm most interested in.

**Comment by SuperMatt** [comment]
I've done some testing at if I set ansible to version 1, it works as expected, so the problem is only with the Ansible feature.

**Comment by jcbhmr** [comment]
Related to #268?

Workaround for now is probably to use a Python base image or feature and run `pipx install ansible` in your postCreateCommand.

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#id13

**Comment by SuperMatt** [comment]
My current workaround is to use version 1 of the Ansible feature rather than 2 (or 2.0.5). Seems to be working well enough for me right now so I'll stick with that, but hopefully this bug gets fixed.

**Comment by jcbhmr** [comment]
Since you seem like a good user use-case example, what's your opinion on #294 ?

**Comment by SuperMatt** [comment]
I really have no opinions about this right now, I've only been using Dev Containers since earlier today.

**Comment by jcbhmr** [comment]
/re @SuperMatt That's OK too! Hope you enjoy using them. And thanks for reporting this issue!

**Comment by danielbraun89** [comment]
Fixed now that oras binary is no longer been used.
