### ISSUE TITLE
Installation issue when using mongosh-homebrew

### ISSUE THREAD

**Issue by sdrzazga** [devcontainers-contrib/features#308]
Hi.

When using `mongosh-homebrew` the container runs into an issue during installation.

_devcontainer.json_
```
{
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu-22.04",
  "features": {
    "ghcr.io/devcontainers-contrib/features/mongosh-homebrew:1": {}
  }
}
```

_creation.log_
```
#16 285.1 ==> Installing mongosh dependency: brotli
2023-02-02 16:57:03.783Z: #16 285.4 fatal: not in a git directory
2023-02-02 16:57:03.936Z: #16 285.4 Error: Command failed with exit 128: git2023-02-02 16:57:03.943Z: 
#16 285.4 ERROR: Feature "MongoDB Shell (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mongosh-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mongosh-homebrew for help troubleshooting this error.
2023-02-02 16:57:04.316Z: #16 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/mongosh-homebrew_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 1
------
 > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/mongosh-homebrew_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#16 282.9 ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:1b8e667c9dfa32f37fc2b05d89eca46625215baa773309290e1ec0e045dc6ec5?se=2023-02-02T17%3A05%3A00Z&sig=UjCPpUZw2m0KMNlt6MlyBf3ozvsPObJSH0escORNJfE%3D&sp=r&spr=https&sr=b&sv=2019-12-12
#16 283.2 ==> Fetching mongosh
#16 283.2 ==> Downloading https://ghcr.io/v2/homebrew/core/mongosh/manifests/1.6.2
#16 284.3 ==> Downloading https://ghcr.io/v2/homebrew/core/mongosh/blobs/sha256:dac3bf86e760aa4054179f7e4722a9bc7e9b9fd0a3125d8ce6e34ee43dfacffe
#16 284.7 ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:dac3bf86e760aa4054179f7e4722a9bc7e9b9fd0a3125d8ce6e34ee43dfacffe?se=2023-02-02T17%3A05%3A00Z&sig=3JnPJxtLIL5lxmnJoAM%2Bmmp8Clyec7F6mduCNZUgIl8%3D&sp=r&spr=https&sr=b&sv=2019-12-12
#16 285.1 ==> Installing dependencies for mongosh: brotli, c-ares, icu4c, libnghttp2, libuv, ca-certificates, openssl@1.1, gdbm, mpdecimal, ncurses, readline, zlib, sqlite, xz, bzip2, expat, libffi, libxcrypt, unzip, libedit, krb5, libtirpc, libnsl, python and node@16
#16 285.1 ==> Installing mongosh dependency: brotli
#16 285.4 fatal: not in a git directory
#16 285.4 Error: Command failed with exit 128: git
#16 285.4 ERROR: Feature "MongoDB Shell (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mongosh-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mongosh-homebrew for help troubleshooting this error.
------
ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/mongosh-homebrew_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 1
2023-02-02 16:57:04.386Z: Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1675356728062 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu-22.04 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-reusable-workflow-1dece9e1379d6062a7ea21f746cf1809-features -f /tmp/devcontainercli-root/container-features/0.28.0-1675356728062/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-02-02 16:57:04.418Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1675356728062 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu-22.04 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-reusable-workflow-1dece9e1379d6062a7ea21f746cf1809-features -f /tmp/devcontainercli-root/container-features/0.28.0-1675356728062/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
2023-02-02 16:57:04.427Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1675356728062 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu-22.04 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-reusable-workflow-1dece9e1379d6062a7ea21f746cf1809-features -f /tmp/devcontainercli-root/container-features/0.28.0-1675356728062/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-02-02 16:57:04.435Z:     at fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1355)
2023-02-02 16:57:04.439Z:     at P7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1291)
2023-02-02 16:57:04.442Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-02-02 16:57:04.452Z:     at async Fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:2093)
2023-02-02 16:57:04.455Z:     at async $f (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:3239)
2023-02-02 16:57:04.460Z:     at async eoe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:17247)
2023-02-02 16:57:04.462Z:     at async Qse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:16993)
2023-02-02 16:57:04.463Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-02-02 16:57:04.465Z: Failed to create container.
=================================================================================
```

**Comment by danielbraun89** [comment]
Thanks for reporting, working on it

**Comment by danielbraun89** [comment]
A fix appears to be adding a ` ` line prior to installing any homebrew package
credit: https://stackoverflow.com/a/71941707/5922329

My guess is debian sources got updated? (or the latest debian container of ms got updated with newer debian?) in a way that caused git to get installed at a higher version (>2.35.2) and started these recent failures which used to work.  ill update all homebrew features promptly
