### ISSUE TITLE
[Bug]: No features seem to install successfully

### ISSUE THREAD

**Issue by pvogel1967** [devcontainers-contrib/features#413]
### Feature id and version

ghcr.io/devcontainers-contrib/features/mongosh-homebrew:1

### Devcontainer base Image

mcr.microsoft.com/devcontainers/universal:2

### What happened?

Any time I add a feature (I've tried mongosh, mongo atlas cli, aws-cli, etc.) the container fails to rebuild and goes into recovery mode.

### Relevant log output

```shell
2023-05-02 23:28:08.394Z: #17 52.04 ERROR: Feature "MongoDB Shell (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mongosh-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mongosh-homebrew for help troubleshooting this error.
2023-05-02 23:28:08.933Z: #17 ERROR: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/mongosh-homebrew_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mongosh-homebrew_1  && cd /tmp/dev-container-features/mongosh-homebrew_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mongosh-homebrew_1]: exit code: 1
------
 > [dev_containers_target_stage 5/6] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=mongosh-homebrew_1,target=/tmp/build-features-src/mongosh-homebrew_1     cp -ar /tmp/build-features-src/mongosh-homebrew_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mongosh-homebrew_1  && cd /tmp/dev-container-features/mongosh-homebrew_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mongosh-homebrew_1:
#17 51.83   File "click.core", line 760, in invoke
#17 51.83   File "typer.main", line 683, in wrapper
#17 51.83   File "nanolayer.cli.install", line 64, in install_devcontainer_feature
#17 51.83   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 131, in install
#17 51.83   File "nanolayer.utils.invoker", line 56, in invoke
#17 51.83 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmprvnwptia && chmod +x -R . && _REMOTE_USER="codespace" _REMOTE_USER_HOME="/home/codespace" PACKAGE="mongosh" VERSION="latest" INSTALLATION_FLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-Jz1ZMvYjXW/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
#17 51.93 Sentry is attempting to send 2 pending error messages
#17 51.93 Waiting up to 2 seconds
#17 51.93 Press Ctrl-C to quit
#17 52.04 ERROR: Feature "MongoDB Shell (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mongosh-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mongosh-homebrew for help troubleshooting this error.
------
ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/mongosh-homebrew_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mongosh-homebrew_1  && cd /tmp/dev-container-features/mongosh-homebrew_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mongosh-homebrew_1]: exit code: 1
2023-05-02 23:28:08.954Z: Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.37.0-1683070025995 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-scoreview-react-793fa66389abd0497a61c5f4ed2e3f8f8cebcc4a7b53dc5b4e645a911eff66bd-features -f /tmp/devcontainercli-root/container-features/0.37.0-1683070025995/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-05-02 23:28:08.958Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.37.0-1683070025995 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-scoreview-react-793fa66389abd0497a61c5f4ed2e3f8f8cebcc4a7b53dc5b4e645a911eff66bd-features -f /tmp/devcontainercli-root/container-features/0.37.0-1683070025995/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-05-02 23:28:08.959Z:     at wse (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:3264)
2023-05-02 23:28:08.963Z:     at K7 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:3200)
2023-05-02 23:28:08.966Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-05-02 23:28:08.972Z:     at async Hse (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:2626)
2023-05-02 23:28:08.979Z:     at async Ch (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:3741)
2023-05-02 23:28:08.983Z:     at async cae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17376)
2023-05-02 23:28:08.987Z:     at async uae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17117)
2023-05-02 23:28:08.994Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.37.0-1683070025995 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-scoreview-react-793fa66389abd0497a61c5f4ed2e3f8f8cebcc4a7b53dc5b4e645a911eff66bd-features -f /tmp/devcontainercli-root/container-features/0.37.0-1683070025995/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
2023-05-02 23:28:09.000Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-05-02 23:28:09.004Z: Failed to create container.
```

**Comment by minhio** [comment]
likely because of this bug https://github.com/devcontainers-contrib/features/issues/412

**Comment by danielbraun89** [comment]
@pvogel1967 @minhio thank you both so much for reporting this I really wish I saw it earlier,
I tracked the problem to an implementation bug I had in the homebrew-package feature which caused it to fail specificly on latest `mcr.microsoft.com/devcontainers/universal:2`  image

The bug was simply the sourcing of `/etc/profile` from inside a bash context which had command line args in it. 
these command line args then leaked to the `/etc/profile` file and caused the script to fail

The reason it started failing only now is that the latest universal image which released 5 days ago https://github.com/devcontainers/images/tree/main/src/universal/history  had an new logic in which /etc/profile sourcing `/usr/local/nvs/nvs.sh` which then reads the leaked command line args, and try to install node with bad version.

Intersting enough, without you reporting the issue I would have never known it occured - as all the tests are using the `base:debian` image and were not susceptible for it - so thanks again! 

I my reproduction setup the latest update should solved the issue, please try the latest versions of any of the homebrew based feature
