### ISSUE TITLE
[Bug]: I am not able to reopen my dev container

### ISSUE THREAD

**Issue by localhostxx** [devcontainers-contrib/features#450]
### Feature id and version

ghcr.io/devcontainers-contrib/features/fd:1

### What happened?

When I was trying to open a dev container from a json, It was failing due to the above feature, the issue started here

#0 13.40 nanolayer.installers.gh_release.resolvers.asset_resolver.AssetResolver.AssetResolverError: Too many matches found: ['fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz', 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz']

### Relevant log output

```shell
> [devcontainer dev_containers_target_stage 15/17] RUN chmod -R 0755 /tmp/dev-container-features/fd_6 && cd /tmp/dev-container-features/fd_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.164 ==========================
[2023-06-07T12:32:31.627Z] =================================================
#0 0.164 Feature       : fd (via Github Releases)
#0 0.164 Description   : fd is a simple, fast and user-friendly alternative to 'find'.
#0 0.164 Id            : ghcr.io/devcontainers-contrib/features/fd
#0 0.164 Version       : 1.0.11
#0 0.164 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/fd
#0 0.164 Options       :
#0 0.164     VERSION="latest"
#0 0.164 ===========================================================================
[2023-06-07T12:32:31.628Z] 
#0 0.167 bash: cannot set terminal process group (1): Inappropriate ioctl for device
#0 0.167 bash: no job control in this shell
#0 6.227 nanolayer
#0 11.72 cd /tmp/tmpo822hkn5 && chmod +x -R . && _REMOTE_USER="codespace" _REMOTE_USER_HOME="/home/codespace" REPO="sharkdp/fd" BINARYNAMES="fd" VERSION="latest" ASSETREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-JGZvzE0sFQ/nanolayer" bash  -i  +H ./install.sh
#0 11.72 Found a pre-existing nanolayer which were given in env varialbe: /tmp/nanolayer-JGZvzE0sFQ/nanolayer

#0 13.32 'fd-musl_8.7.0_amd64.deb' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd-musl_8.7.0_i686.deb' filtered by '(\.deb|\.rpm|\.pkg|\.apk|\.[Aa]ppImage|\.snap)' (negative)

#0 13.33 'fd-v8.7.0-i686-pc-windows-msvc.zip' filtered by '(windows|Windows|WINDOWS|win32|\-win\-|\.msi$|.msixbundle$|\.e
[2023-06-07T12:32:31.628Z] xe$)' (negative)

#0 13.33 'fd-v8.7.0-x86_64-apple-darwin.tar.gz' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd-v8.7.0-x86_64-pc-windows-gnu.zip' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd-v8.7.0-x86_64-pc-windows-msvc.zip' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd-v8.7.0-x86_64-unknown-linux-gnu.tar.gz' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd-v8.7.0-x86_64-unknown-linux-musl.tar.gz' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd_8.7.0_amd64.deb' filtered by '([Aa]md64|-x64|x64|x86[_-]64)' (negative)

#0 13.33 'fd_8.7.0_arm64.deb' filtered by '(\.deb|\.rpm|\.pkg|\.apk|\.[Aa]ppImage|\.snap)' (negative)

#0 13.33 'fd_8.7.0_armhf.deb' filtered by '([Aa][Rr][Mm]hf)' (negative)

#0 13.33 'fd_8.7.0_i686.deb' filtered by '(\.deb|\.rpm|\.pkg|\.apk|\.[Aa]ppImage|\.snap)' (negative)

#0 13.33 'fd-v8.7.0-aarch64-unknown-linux-gnu.tar.gz' filtered by '([Aa]rm64|ARM64|-ARM)' 
[2023-06-07T12:32:31.628Z] 
#0 13.33 'fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz' filtered by '([Aa]rm64|ARM64|-ARM)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz' filtered by '([Aa]rm64|ARM64|-ARM)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz' filtered by '([Aa]rm64|ARM64|-ARM)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-musl.tar.gz' filtered by '([Aa]rm64|ARM64|-ARM)' 

#0 13.33 'fd-v8.7.0-aarch64-unknown-linux-gnu.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-musl.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-aarch64-unknown-linux-gnu.tar.gz' filtered by '.*static.*' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz' filtered by '.*static.*' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz' filtere
[2023-06-07T12:32:31.628Z] d by '.*static.*' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz' filtered by '.*static.*' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-musl.tar.gz' filtered by '.*static.*' 

#0 13.33 'fd-v8.7.0-aarch64-unknown-linux-gnu.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-i686-unknown-linux-musl.tar.gz' filtered by '(?i)(debian)' 

#0 13.33 'fd-v8.7.0-arm-unknown-linux-musleabihf.tar.gz' filtered by '(?i)(alpine|musl)' (negative)

#0 13.33 'fd-v8.7.0-i686-unknown-linux-musl.tar.gz' filtered by '(?i)(alpine|musl)' (negative)

#0 13.33 'fd-v8.7.0-aarch64-unknown-linux-gnu.tar.gz' filtered by '(?i)(arch)' (negative)
[2023-06-07T12:32:31.628Z] 
#0 13.39 Traceback (most recent call last):

#0 13.40   File "<string>", line 1, in <module>

#0 13.40   File "nanolayer.__main__", line 50, in main

#0 13.40   File "typer.main", line 328, in __call__

#0 13.40   File "typer.main", line 311, in __call__

#0 13.40   File "click.core", line 1130, in __call__

#0 13.40   File "typer.core", line 778, in main

#0 13.40   File "typer.core", line 216, in _main

#0 13.40   File "click.core", line 1657, in invoke

#0 13.40   File "click.core", line 1657, in invoke

#0 13.40   File "click.core", line 1404, in invoke
[2023-06-07T12:32:31.628Z] 
#0 13.40   File "click.core", line 760, in invoke

#0 13.40   File "typer.main", line 683, in wrapper

#0 13.40   File "nanolayer.cli.install", line 159, in install_gh_release_binary

#0 13.40   File "nanolayer.installers.gh_release.gh_release_installer", line 163, in install

#0 13.40   File "nanolayer.installers.gh_release.resolvers.asset_resolver", line 292, in resolve

#0 13.40 nanolayer.installers.gh_release.resolvers.asset_resolver.AssetResolver.AssetResolverError: Too many matches found: ['fd-v8.7.0-arm-unknown-linux-gnueabihf.tar.gz', 'fd-v8.7.0-i686-unknown-linux-gnu.tar.gz']

#0 13.50 Sentry is attempting to send 2 pending error messages

#0 13.50 Waiting up to 2 seconds

#0 13.50 Press Ctrl-C to quit

#0 13.75 Traceback (most recent call last):
[2023-06-07T12:32:31.628Z] 
#0 13.75   File "<string>", line 1, in <module>
#0 13.75   File "nanolayer.__main__", line 50, in main
#0 13.75   File "typer.main", line 328, in __call__
#0 13.75   File "typer.main", line 311, in __call__
#0 13.75   File "click.core", line 1130, in __call__
#0 13.75   File "typer.core", line 778, in main
#0 13.75   File "typer.core", line 216, in _main
#0 13.75   File "click.core", line 1657, in invoke
#0 13.75   File "click.core", line 1657, in invoke
#0 13.75   File "click.core", line 1404, in invoke
#0 13.75   File "click.core", line 760, in invoke
#0 13.75   File "typer.main", line 683, in wrapper
#0 13.75   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#0 13.75   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
#0 13.75   File "nanolayer.utils.invoker", line 56, in invoke
#0 13.75 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpo822hkn5 && chmod +x -R . && _REMOTE_USER="codespace" _REMOTE_USE
[2023-06-07T12:32:31.628Z] R_HOME="/home/codespace" REPO="sharkdp/fd" BINARYNAMES="fd" VERSION="latest" ASSETREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-JGZvzE0sFQ/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
[2023-06-07T12:32:31.628Z] 
#0 13.85 Sentry is attempting to send 2 pending error messages
#0 13.85 Waiting up to 2 seconds
#0 13.85 Press Ctrl-C to quit
#0 14.00 ERROR: Feature "fd (via Github Releases)" (ghcr.io/devcontainers-contrib/features/fd) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/fd for help troubleshooting this error.
------
failed to solve: process "/bin/sh -c chmod -R 0755 /tmp/dev-container-features/fd_6 && cd /tmp/dev-container-features/fd_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh" did not complete successfully: exit code: 1
[2023-06-07T12:32:31.632Z] Stop (17438 ms): Run: docker-compose --project-name butler_server_devcontainer -f /Users/guru/Desktop/greyorange/butler_server/.devcontainer/docker-compose.yml -f /Users/guru/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1686141134193.yml build db zookeeper kafka kafka-ui emqx devcontainer
[2023-06-07T12:32:31.632Z] Error: Command failed: docker-compose --project-name butler_server_devcontainer -f /Users/guru/Desktop/greyorange/butler_server/.devcontainer/docker-compose.yml -f /Users/guru/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1686141134193.yml build db zookeeper kafka kafka-ui emqx devcontainer
[2023-06-07T12:32:31.632Z]     at FD (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1912:412)
[2023-06-07T12:32:31.632Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-06-07T12:32:31.632Z]     at async _se (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1912:2381)
[2023-06-07T12:32:31.632Z]     at async Bse (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1894:3170)
[2023-06-07T12:32:31.632Z]     at async Xse (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1961:2799)
[2023-06-07T12:32:31.632Z]     at async vh (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1961:3741)
[2023-06-07T12:32:31.632Z]     at async gae (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:10213)
[2023-06-07T12:32:31.633Z]     at async mae (/Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:9954)
[2023-06-07T12:32:31.635Z] Stop (28911 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/guru/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-7ba27fb0-2819-4e83-a394-d99ad7b20b1b1686141121703 --workspace-folder /Users/guru/Desktop/greyorange/butler_server --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/guru/Desktop/greyorange/butler_server --id-label devcontainer.config_file=/Users/guru/Desktop/greyorange/butler_server/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/guru/Desktop/greyorange/butler_server/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-07T12:32:31.635Z] Exit code 1
[2023-06-07T12:32:31.637Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/guru/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/guru/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-7ba27fb0-2819-4e83-a394-d99ad7b20b1b1686141121703 --workspace-folder /Users/guru/Desktop/greyorange/butler_server --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/guru/Desktop/greyorange/butler_server --id-label devcontainer.config_file=/Users/guru/Desktop/greyorange/butler_server/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/guru/Desktop/greyorange/butler_server/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-07T12:32:31.637Z] Exit code 1
```

**Comment by danielbraun89** [comment]
I have improved the ARM asset detection in latest version, please try `ghcr.io/devcontainers-contrib/features/fd:1.0.12`
