### ISSUE TITLE
[Bug]: nanolayer.utils.invoker.Invoker.InvokerException installing CUE (via asdf) (cue-asdf)

### ISSUE THREAD

**Issue by code-n-go** [devcontainers-contrib/features#489]
### Feature id and version

ghcr.io/devcontainers-contrib/features/cue-asdf:2

### Devcontainer base Image

mcr.microsoft.com/vscode/devcontainers/go:1.20-bookworm

### What happened?

I don't completely understand the logs; however, it appears that maybe it can't obtain cue 0.6.0-0.dev from the specified source?  It's the only plugin I'm having issues with.

### Relevant log output

```shell
#0 5.972 ��� Downloading and installing cue 0.6.0-0.dev...

#0 5.980   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

#0 5.981                                  Dload  Upload   Total   Spent    Left  Speed

#0 5.981 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   128  100   128    0     0    753      0 --:--:-- --:--:-- --:--:--   757

#0 6.153 

#0 6.159   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

#0 6.159                                  Dload  Upload   Total   Spent    Left  Speed

#0 6.159 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     56      0 --:--:-- --:--:-- --:--:--    56
100     9  100     9    0     0     56      0 --:--:-- --:--:-- --:--:--    56

#0 6.324 

#0 6.324 gzip: stdin: not in gzip format

#0 6.324 tar: Child returned status 1

#0 6.324 tar: Error is not recoverable: exiting now

#0 6.325 Fail: Could not uncompress

#0 6.326 Fail: An error occurred

#0 6.622 version 0.6.0-0.dev is not installed for cue

#0 6.658 Traceback (most recent call last):
#0 6.659   File "<string>", line 1, in <module>
#0 6.659   File "nanolayer.__main__", line 50, in main
#0 6.659   File "typer.main", line 328, in __call__
#0 6.659   File "typer.main", line 311, in __call__
#0 6.659   File "click.core", line 1130, in __call__
#0 6.659   File "typer.core", line 778, in main
#0 6.659   File "typer.core", line 216, in _main
#0 6.659   File "click.core", line 1657, in invoke
#0 6.659   File "click.core", line 1657, in invoke
#0 6.659   File "click.core", line 1404, in invoke
#0 6.659   File "click.core", line 760, in invoke
#0 6.660   File "typer.main", line 683, in wrapper
#0 6.660   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#0 6.660   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
#0 6.660   File "nanolayer.utils.invoker", line 56, in invoke
#0 6.660 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpoxn4zzpl && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" PLUGIN="cue" VERSION="latest" PLUGINREPO="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-aMaCS52TVq/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
#0 6.784 ERROR: Feature "CUE (via asdf)" (ghcr.io/devcontainers-contrib/features/cue-asdf) failed to install! Look at the 
[2023-07-03T22:23:30.188Z] documentation at http://github.com/devcontainers-contrib/features/tree/main/src/cue-asdf for help troubleshooting this error.
------
failed to solve: process "/bin/sh -c chmod -R 0755 /tmp/dev-container-features/cue-asdf_1 && cd /tmp/dev-container-features/cue-asdf_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh" did not complete successfully: exit code: 1
[2023-07-03T22:23:30.195Z] Stop (7334 ms): Run: docker compose --project-name play_x00_devcontainer -f /home/debian/play_x00/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-debian/docker-compose/docker-compose.devcontainer.build-1688423002861.yml build
[2023-07-03T22:23:30.199Z] Error: Command failed: docker compose --project-name play_x00_devcontainer -f /home/debian/play_x00/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-debian/docker-compose/docker-compose.devcontainer.build-1688423002861.yml build
[2023-07-03T22:23:30.199Z]     at Ux (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:1969:412)
[2023-07-03T22:23:30.200Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-07-03T22:23:30.200Z]     at async fte (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:1969:2381)
[2023-07-03T22:23:30.200Z]     at async cte (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:1951:3170)
[2023-07-03T22:23:30.200Z]     at async Ote (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:3833)
[2023-07-03T22:23:30.200Z]     at async Hf (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:4775)
[2023-07-03T22:23:30.200Z]     at async Qre (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10371)
[2023-07-03T22:23:30.200Z]     at async Zre (/home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10112)
[2023-07-03T22:23:30.205Z] Stop (14023 ms): Run in Host: /home/debian/.vscode-remote-containers/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node /home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-467b38cb-aced-49fc-b5c9-422997ddcf911688422995164 --workspace-folder /home/debian/play_x00 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/debian/play_x00 --id-label devcontainer.config_file=/home/debian/play_x00/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/debian/play_x00/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-07-03T22:23:30.205Z] Exit code 1
[2023-07-03T22:23:30.207Z] Command failed: /home/debian/.vscode-remote-containers/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node /home/debian/.vscode-remote-containers/dist/dev-containers-cli-0.295.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-467b38cb-aced-49fc-b5c9-422997ddcf911688422995164 --workspace-folder /home/debian/play_x00 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/debian/play_x00 --id-label devcontainer.config_file=/home/debian/play_x00/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/debian/play_x00/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-07-03T22:23:30.207Z] Exit code 1
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features
