### ISSUE TITLE
[Bug]: mysql-homebrew fail to install

### ISSUE THREAD

**Issue by c01o** [devcontainers-contrib/features#523]
### Feature id and version

ghcr.io/devcontainers-contrib/features/mysql-homebrew:1

### Devcontainer base Image

mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

### What happened?

Installation of `curl` somehow fails.

I confirmed the latest linuxbrew (4.1.10) installed on a brand new `ubuntu:latest` container successfully run `brew install mysql` without any error.

### Relevant log output

```shell
...
#0 300.4 ==> Installing mysql dependency: rtmpdump
#0 300.4 ==> Downloading https://ghcr.io/v2/homebrew/core/rtmpdump/manifests/2.4-20151223
#0 300.4 Already downloaded: /home/node/.cache/Homebrew/downloads/b40cb4d6b301aad8ce26f9deb74a74c0d98d1868d19881f9bff55b81d6f11e50--rtmpdump-2.4-20151223_3.bottle_manifest.json
#0 300.5 ==> Pouring rtmpdump--2.4-20151223_3.x86_64_linux.bottle.tar.gz
#0 301.8       /home/linuxbrew/.linuxbrew/Cellar/rtmpdump/2.4-20151223_3: 20 files, 625.2KB
#0 301.9 ==> Installing mysql dependency: curl
#0 301.9 ==> Downloading https://ghcr.io/v2/homebrew/core/curl/manifests/8.2.1
#0 301.9 Already downloaded: /home/node/.cache/Homebrew/downloads/875e27d50739f565f91d00393bfc6d87397e86aae4fbe5133f9e67889c034d5c--curl-8.2.1.bottle_manifest.json
#0 302.1 ==> Pouring curl--8.2.1.x86_64_linux.bottle.tar.gz
#0 303.1 Error: /home/linuxbrew/.linuxbrew/Cellar/curl/8.2.1 is not a directory
#0 303.3 + clean_up
#0 303.3 + ARG=1
#0 303.3 + rm -rf /tmp/nanolayer-OOzYfRjCBU
#0 303.3 + exit 1
#0 303.3 Traceback (most recent call last):
#0 303.3   File "<string>", line 1, in <module>
#0 303.3   File "nanolayer.__main__", line 50, in main
#0 303.3   File "typer.main", line 328, in __call__
#0 303.3   File "typer.main", line 311, in __call__
#0 303.3   File "click.core", line 1130, in __call__
#0 303.3   File "typer.core", line 778, in main
#0 303.3   File "typer.core", line 216, in _main
#0 303.3   File "click.core", line 1657, in invoke
#0 303.3   File "click.core", line 1657, in invoke
#0 303.3   File "click.core", line 1404, in invoke
#0 303.3   File "click.core", line 760, in invoke
#0 303.3   File "typer.main", line 683, in wrapper
#0 303.3   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#0 303.3   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
#0 303.3   File "nanolayer.utils.invoker", line 56, in invoke
#0 303.3 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpwuut_duk && chmod +x -R . && _REMOTE_USER="node" _REMOTE_USER_HOME="/home/node" PACKAGE="mysql" VERSION="latest" INSTALLATION_FLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-t4VvB2O0U7/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
#0 303.5 ERROR: Feature "MySQL (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mysql-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mysql-homebrew for help troubleshooting this error.
------
Dockerfile.extended:24
--------------------
  23 |     
  24 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=mysql-homebrew_0,target=/tmp/build-features-src/mysql-homebrew_0 \
  25 | >>>     cp -ar /tmp/build-features-src/mysql-homebrew_0 /tmp/dev-container-features \
  26 | >>>  && chmod -R 0755 /tmp/dev-container-features/mysql-homebrew_0 \
  27 | >>>  && cd /tmp/dev-container-features/mysql-homebrew_0 \
  28 | >>>  && chmod +x ./devcontainer-features-install.sh \
  29 | >>>  && ./devcontainer-features-install.sh \
  30 | >>>  && rm -rf /tmp/dev-container-features/mysql-homebrew_0
  31 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/mysql-homebrew_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mysql-homebrew_0  && cd /tmp/dev-container-features/mysql-homebrew_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mysql-homebrew_0" did not complete successfully: exit code: 1
[318524 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-USERNAME/container-features/0.51.1-1694330751259 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-b43057e0d5f03cc068b211e6d1298fdbf838b9ebe05735c7812fd63eb356c92e-bd4876bfbdad84fdaeb93c3e5d0161ac5b4620af37670122a6bda86df2890b43-features -f /tmp/devcontainercli-USERNAME/container-features/0.51.1-1694330751259/Dockerfile.extended /tmp/devcontainercli-USERNAME/empty-folder
[318525 ms]     at gAA (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:1066)
[318525 ms]     at FK (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:1002)
[318525 ms]     at runMicrotasks (<anonymous>)
[318525 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[318525 ms]     at async FAA (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[318525 ms]     at async GC (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[318525 ms]     at async VeA (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:12240)
[318525 ms]     at async WeA (/home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:11981)
[318526 ms] Exit code 1
[318529 ms] Command failed: /home/USERNAME/.vscode-remote-containers/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/USERNAME/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-10f54970-e770-4f86-99c7-85d74b0825001694330748244 --workspace-folder /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/b43057e0d5f03cc068b211e6d1298fdbf838b9ebe05735c7812fd63eb356c92e --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\colon\vscode\hokensyo_viewer --id-label devcontainer.config_file=/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/b43057e0d5f03cc068b211e6d1298fdbf838b9ebe05735c7812fd63eb356c92e/.devcontainer/devcontainer.json --log-level debug --log-format json --config /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/b43057e0d5f03cc068b211e6d1298fdbf838b9ebe05735c7812fd63eb356c92e/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[318529 ms] Exit code 1
```
```

**Comment by Yvens16** [comment]
Hello, did you found out why ?

**Comment by ha0min** [comment]
I am encounting the same issue:

when I try to rebuild the codespace with the mysql-homebrew feature, it failed to build the image and crushed:
```sh
2024-02-07 05:04:00.979Z: #16 197.6 ==> Installing mysql dependency: systemd
2024-02-07 05:04:00.995Z: 
#16 197.6 ==> Downloading https://ghcr.io/v2/homebrew/core/systemd/manifests/255.3

#16 197.6 Already downloaded: /home/vscode/.cache/Homebrew/downloads/0197c3269b38c869b3ebaa0c581c42f03013dd2daa9f24c3e5af14f376e2fd09--systemd-255.3.bottle_manifest.json

2024-02-07 05:04:01.281Z: #16 198.0 ==> Pouring systemd--255.3.x86_64_linux.bottle.tar.gz

2024-02-07 05:04:10.923Z: #16 207.6 Error: Too many open files

2024-02-07 05:04:11.224Z: #16 207.9 + clean_up

#16 207.9 + ARG=1

#16 207.9 + rm -rf /tmp/nanolayer-8cVfMiu1CV

#16 207.9 + exit 1
2024-02-07 05:04:11.227Z: 
2024-02-07 05:04:11.346Z: #16 208.1 Traceback (most recent call last):
2024-02-07 05:04:11.455Z: #16 208.1   File "<string>", line 1, in <module>
#16 208.1   File "nanolayer.__main__", line 50, in main
#16 208.1   File "typer.main", line 328, in __call__
#16 208.1   File "typer.main", line 311, in __call__
#16 208.1   File "click.core", line 1130, in __call__
#16 208.1   File "typer.core", line 778, in main
#16 208.1   File "typer.core", line 216, in _main
#16 208.1   File "click.core", line 1657, in invoke
#16 208.1   File "click.core", line 1657, in invoke
#16 208.1   File "click.core", line 1404, in invoke
#16 208.1   File "click.core", line 760, in invoke
#16 208.1   File "typer.main", line 683, in wrapper
#16 208.1   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#16 208.1   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
#16 208.1   File "nanolayer.utils.invoker", line 56, in invoke
#16 208.1 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmp8zm0ckf0 && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" PACKAGE="mysql" VERSION="latest" INSTALLATION_FLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-uLhoNWjwxZ/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
#16 208.2 Sentry is attempting to send 2 pending error messages
#16 208.2 Waiting up to 2 seconds
#16 208.2 Press Ctrl-C to quit
2024-02-07 05:04:11.609Z: #16 208.3 ERROR: Feature "MySQL (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mysql-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mysql-homebrew for help troubleshooting this error.
2024-02-07 05:04:12.184Z: #16 ERROR: process "/bin/sh -c cp -ar /tmp/build-features-src/mysql-homebrew_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mysql-homebrew_0  && cd /tmp/dev-container-features/mysql-homebrew_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mysql-homebrew_0" did not complete successfully: exit code: 1
2024-02-07 05:04:12.394Z: ------
 > [app dev_containers_target_stage 4/7] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=mysql-homebrew_0,target=/tmp/build-features-src/mysql-homebrew_0     cp -ar /tmp/build-features-src/mysql-homebrew_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/mysql-homebrew_0  && cd /tmp/dev-container-features/mysql-homebrew_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/mysql-homebrew_0:
208.1   File "click.core", line 760, in invoke
208.1   File "typer.main", line 683, in wrapper2024-02-07 05:04:12.411Z: 
208.1   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
208.1   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
208.1   File "nanolayer.utils.invoker", line 56, in invoke
208.1 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmp8zm0ckf0 && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" PACKAGE="mysql" VERSION="latest" INSTALLATION_FLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-uLhoNWjwxZ/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
208.2 Sentry is attempting to send 2 pending error messages2024-02-07 05:04:12.424Z: 
208.2 Waiting up to 2 seconds
208.2 Press Ctrl-C to quit
208.3 ERROR: Feature "MySQL (via Homebrew)" (ghcr.io/devcontainers-contrib/features/mysql-homebrew) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/mysql-homebrew for help troubleshooting this error.
------
```

**Comment by iamxiaobing47** [comment]
The defect remains.

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features
