### ISSUE TITLE
[Bug]: http 401/403 error on installation poetry feature

### ISSUE THREAD

**Issue by JJ-Author** [devcontainers-contrib/features#580]
### Feature id and version

ghcr.io/devcontainers-contrib/features/poetry:2.0.17

### Devcontainer base Image

mcr.microsoft.com/devcontainers/python:1-3.10-bullseye

### What happened?

http 401/403 error on installation -> image build failure

### Relevant log output

```shell
[+] Building 3.5s (5/13)                                                        
 => => transferring dockerfile: 2.30kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/python:1  0.4s
 => [internal] load metadata for docker.io/library/dev_container_feature_  0.0s
 => [dev_containers_feature_content_source 1/1] FROM docker.io/library/de  0.0s
 => [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com  3.1s
[+] Building 1090.7s (13/13) FINISHED                                           
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 2.30kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/python:1  0.4s
 => [internal] load metadata for docker.io/library/dev_container_feature_  0.0s
 => [dev_containers_feature_content_source 1/1] FROM docker.io/library/de  0.0s
 => [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.co  30.7s
 => => resolve mcr.microsoft.com/devcontainers/python:1-3.10-bullseye@sha  0.0s
 => => sha256:15bc9cc853b9d797cab0aa4b43ba7792a031ba9f6 21.27kB / 21.27kB  0.0s
 => => sha256:7faaa42ac0c18c9baf539c97a5c8f042d02a77b05 55.06MB / 55.06MB  1.1s
 => => sha256:f124d049a72aebbe5ef2fd589921f51fde08aa5b6 54.60MB / 54.60MB  1.9s
 => => sha256:00e45f2f600f9cd1bb66e8eba74e488c43086d9b961 1.61kB / 1.61kB  0.0s
 => => sha256:a2bbe50ba4aaf4ff2a60f3fd7e048d2399072e13d62 3.74kB / 3.74kB  0.0s
 => => sha256:1efd1e766326156b6d61b11d929f560cb73024ca0 15.77MB / 15.77MB  1.6s
 => => sha256:6c200adf1811433c67c208599f5f71578e5237c 196.90MB / 196.90MB  4.1s
 => => extracting sha256:7faaa42ac0c18c9baf539c97a5c8f042d02a77b05380cb57  2.6s
 => => sha256:cf6de90d25814ceb2ec0fbdca304824fa4b33e69a66 6.29MB / 6.29MB  2.1s
 => => sha256:040bef6a0860c6a7a2e78fdcf951f549812360a80 17.34MB / 17.34MB  2.5s
 => => sha256:5d720fba753dcef51da69574905f70debb7f87046fcfc38 244B / 244B  2.3s
 => => sha256:005b1836ca250472d8d7c81b4e0367e2cc7b9008813 3.08MB / 3.08MB  2.8s
 => => sha256:7a3934d9215542d458a7ff4573ec2208b00ad3335 14.22MB / 14.22MB  3.5s
 => => sha256:6ab414987519a020f9f27fa5502920b05347afb5eb6 6.02MB / 6.02MB  3.6s
 => => sha256:60e506a1081b3deaec52555570fd70cf5520645b496cea2 412B / 412B  3.7s
 => => sha256:344c1489cedbbbe5e176a8fa6d30ef4a7f4985414d8d555 134B / 134B  3.8s
 => => sha256:821e6721761e2ea3a2c5f3124e1960b84836fc5425652d2 225B / 225B  3.9s
 => => extracting sha256:1efd1e766326156b6d61b11d929f560cb73024ca0ff2a896  0.6s
 => => sha256:4ce2026e3f02daf3d60b053e4104207cae90c8dcd224ac2 237B / 237B  4.0s
 => => sha256:48fc9fff08c9926a93513d0276d0203cea8a7d1c1 86.46MB / 86.46MB  6.8s
 => => sha256:fc1c640ceb46abae406822b19ec313f01a45d1892 63.65MB / 63.65MB  6.2s
 => => sha256:52f11c36d55b6517a76ff0e13dea5fe6b421f7ef29f 2.26MB / 2.26MB  4.6s
 => => extracting sha256:f124d049a72aebbe5ef2fd589921f51fde08aa5b66cfa8cf  2.7s
 => => sha256:5085236ddc862638b8b75d1f0b81c6b6b85b9a3f3 57.36MB / 57.36MB  8.1s
 => => extracting sha256:6c200adf1811433c67c208599f5f71578e5237cfd9be60d6  8.1s
 => => extracting sha256:cf6de90d25814ceb2ec0fbdca304824fa4b33e69a662b21a  0.4s
 => => extracting sha256:040bef6a0860c6a7a2e78fdcf951f549812360a80e5dcb34  0.8s
 => => extracting sha256:5d720fba753dcef51da69574905f70debb7f87046fcfc38f  0.0s
 => => extracting sha256:005b1836ca250472d8d7c81b4e0367e2cc7b90088139cf33  0.3s
 => => extracting sha256:7a3934d9215542d458a7ff4573ec2208b00ad3335c7e9ecb  0.3s
 => => extracting sha256:6ab414987519a020f9f27fa5502920b05347afb5eb629dc2  0.5s
 => => extracting sha256:60e506a1081b3deaec52555570fd70cf5520645b496cea24  0.0s
 => => extracting sha256:344c1489cedbbbe5e176a8fa6d30ef4a7f4985414d8d555c  0.0s
 => => extracting sha256:821e6721761e2ea3a2c5f3124e1960b84836fc5425652d24  0.0s
 => => extracting sha256:4ce2026e3f02daf3d60b053e4104207cae90c8dcd224ac23  0.0s
 => => extracting sha256:48fc9fff08c9926a93513d0276d0203cea8a7d1c17be3312  5.1s
 => => extracting sha256:fc1c640ceb46abae406822b19ec313f01a45d18929b54062  2.0s
 => => extracting sha256:52f11c36d55b6517a76ff0e13dea5fe6b421f7ef29fd9d8a  0.2s
 => => extracting sha256:5085236ddc862638b8b75d1f0b81c6b6b85b9a3f3d57908b  3.7s
 => [dev_containers_feature_content_normalize 2/3] COPY --from=dev_contai  5.2s
 => [dev_containers_target_stage 2/6] RUN mkdir -p /tmp/dev-container-fea  5.7s
 => [dev_containers_feature_content_normalize 3/3] RUN chmod -R 0755 /tmp  0.7s
 => [dev_containers_target_stage 3/6] COPY --from=dev_containers_feature_  0.0s
 => [dev_containers_target_stage 4/6] RUN echo "_CONTAINER_USER_HOME=$( (  0.7s
 => [dev_containers_target_stage 5/6] COPY --chown=root:root --from=dev_c  0.0s
 => ERROR [dev_containers_target_stage 6/6] RUN chmod -R 0755 /tmp/dev  1053.0s
------
 > [dev_containers_target_stage 6/6] RUN chmod -R 0755 /tmp/dev-container-features/poetry_0 && cd /tmp/dev-container-features/poetry_0 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#13 0.590 ===========================================================================
#13 0.590 Feature       : Poetry (via pipx)
#13 0.590 Description   : Poetry is a tool for dependency management and packaging in Python.
#13 0.590 Id            : ghcr.io/devcontainers-contrib/features/poetry
#13 0.590 Version       : 2.0.17
#13 0.590 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/poetry
#13 0.590 Options       :
#13 0.590     VERSION="latest"
#13 0.590 ===========================================================================
#13 1.875 nanolayer
#13 1052.7 Traceback (most recent call last):
#13 1052.7   File "nanolayer.utils.oci_registry", line 134, in _attempt_request
#13 1052.7   File "urllib.request", line 216, in urlopen
#13 1052.7   File "urllib.request", line 525, in open
#13 1052.7   File "urllib.request", line 634, in http_response
#13 1052.7   File "urllib.request", line 563, in error
#13 1052.7   File "urllib.request", line 496, in _call_chain
#13 1052.7   File "urllib.request", line 643, in http_error_default
#13 1052.7 urllib.error.HTTPError: HTTP Error 401: Unauthorized
#13 1052.7 
#13 1052.7 During handling of the above exception, another exception occurred:
#13 1052.7 
#13 1052.7 Traceback (most recent call last):
#13 1052.7   File "<string>", line 1, in <module>
#13 1052.7   File "nanolayer.__main__", line 50, in main
#13 1052.7   File "typer.main", line 328, in __call__
#13 1052.7   File "typer.main", line 311, in __call__
#13 1052.7   File "click.core", line 1157, in __call__
#13 1052.7   File "typer.core", line 778, in main
#13 1052.7   File "typer.core", line 216, in _main
#13 1052.7   File "click.core", line 1688, in invoke
#13 1052.7   File "click.core", line 1688, in invoke
#13 1052.7   File "click.core", line 1434, in invoke
#13 1052.7   File "click.core", line 783, in invoke
#13 1052.7   File "typer.main", line 683, in wrapper
#13 1052.7   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#13 1052.7   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 113, in install
#13 1052.7   File "nanolayer.installers.devcontainer_feature.oci_feature", line 48, in download_and_extract
#13 1052.7   File "nanolayer.utils.oci_registry", line 178, in download_and_extract_layer
#13 1052.7   File "nanolayer.utils.oci_registry", line 159, in download_layer
#13 1052.7   File "nanolayer.utils.oci_registry", line 195, in get_blob
#13 1052.7   File "nanolayer.utils.oci_registry", line 140, in _attempt_request
#13 1052.7   File "urllib.request", line 216, in urlopen
#13 1052.7   File "urllib.request", line 525, in open
#13 1052.7   File "urllib.request", line 634, in http_response
#13 1052.7   File "urllib.request", line 557, in error
#13 1052.7   File "urllib.request", line 496, in _call_chain
#13 1052.7   File "urllib.request", line 749, in http_error_302
#13 1052.7   File "urllib.request", line 525, in open
#13 1052.7   File "urllib.request", line 634, in http_response
#13 1052.7   File "urllib.request", line 563, in error
#13 1052.7   File "urllib.request", line 496, in _call_chain
#13 1052.7   File "urllib.request", line 643, in http_error_default
#13 1052.7 urllib.error.HTTPError: HTTP Error 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
#13 1052.9 ERROR: Feature "Poetry (via pipx)" (ghcr.io/devcontainers-contrib/features/poetry) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/poetry for help troubleshooting this error.
------
error: failed to solve: executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/poetry_0 && cd /tmp/dev-container-features/poetry_0 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 1
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features
