### ISSUE TITLE
Too many matches found: ['ko_0.15.2_Linux_arm64.tar.gz', 'ko_Linux_arm64.tar.gz']

### ISSUE THREAD

**Issue by lmilbaum** [devcontainers-contrib/features#588]
### Feature id and version

ghcr.io/devcontainers-contrib/features/ko:1.0.9

### Devcontainer base Image

mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04

### What happened?

The devcontainer build is broken on mac Mac M1

### Relevant log output

```shell
[17 ms] Dev Containers 0.348.0 in VS Code 1.87.1 (1e790d77f81672c49be070e04474901747115651).
[17 ms] Start: Resolving Remote
[24 ms] Setting up container for folder or workspace: /Users/lmilbaum/repos/github.com/lmilbaum/pipeline
[24 ms] Context: desktop-linux
[27 ms] Start: Check Docker is running
[27 ms] Start: Run: docker version
[71 ms] Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:18:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:21 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[73 ms] Start: Run: docker volume ls -q
[110 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --filter label=vsch.quality=stable
[147 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --filter label=devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json
[210 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline
[261 ms] ProxyResolver#loadSystemCertificates count
[261 ms] ProxyResolver#loadSystemCertificates count filtered
[262 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/lmilbaum/repos/github.com/lmilbaum/pipeline --id-label devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --id-label devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --mount-workspace-git-root
[420 ms] @devcontainers/cli 0.56.2. Node.js v18.17.1. darwin 23.4.0 arm64.
[420 ms] Start: Run: git rev-parse --show-cdup
[427 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --filter label=devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json
[470 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lmilbaum/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-3a8dcda8-acc9-4cf4-acf7-b28c3d665db31710017376034 --workspace-folder /Users/lmilbaum/repos/github.com/lmilbaum/pipeline --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --id-label devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[628 ms] @devcontainers/cli 0.56.2. Node.js v18.17.1. darwin 23.4.0 arm64.
[628 ms] Start: Run: docker buildx version
[765 ms] github.com/docker/buildx v0.12.1-desktop.4 6996841df2f61988c2794d84d33205368f96c317
[765 ms] 
[765 ms] Start: Resolving Remote
[766 ms] Start: Run: git rev-parse --show-cdup
[773 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --filter label=devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json
[809 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
[848 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/go:1.3.0'...
[848 ms] * Processing feature: ghcr.io/devcontainers/features/go:1.3.0
[849 ms] Loading 3 extra certificates from /var/folders/r6/rtdzvsy54cxcxql560gv7q840000gn/T/vsch/certificates-4dc6cefa099549e31f257f12215099bbc19fd1e4bf49d2cc7e9bad56335ec53d.pem.
[1165 ms] Start: Run: docker-credential-desktop get
[1896 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2230 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers-contrib/features/ko:1.0.9'...
[2230 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/ko:1.0.9
[2583 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/gh-release
[2913 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers-contrib/features/pre-commit:2.0.17'...
[2913 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/pre-commit:2.0.17
[3215 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/pipx-package
[3516 ms] * Processing feature: ghcr.io/devcontainers/features/python
[3840 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[3840 ms] Soft-dependency 'ghcr.io/devcontainers-contrib/features/gh-release' is not required.  Removing from installation order...
[3840 ms] Soft-dependency 'ghcr.io/devcontainers/features/python' is not required.  Removing from installation order...
[3841 ms] Soft-dependency 'ghcr.io/devcontainers-contrib/features/pipx-package' is not required.  Removing from installation order...
[3842 ms] * Fetching feature: ko_0_oci
[4313 ms] * Fetched feature: ko_0_oci version 1.0.9
[4313 ms] * Fetching feature: pre-commit_1_oci
[4835 ms] * Fetched feature: pre-commit_1_oci version 2.0.17
[4835 ms] * Fetching feature: go_2_oci
[5308 ms] * Fetched feature: go_2_oci version 1.3.0
[5315 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/r6/rtdzvsy54cxcxql560gv7q840000gn/T/devcontainercli/container-features/0.56.2-1710017377179 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pipeline-838924657317ed7625495b4f5866ac92012a218a3d2f3cdfd552017e701de02b-features -f /var/folders/r6/rtdzvsy54cxcxql560gv7q840000gn/T/devcontainercli/container-features/0.56.2-1710017377179/Dockerfile.extended /Users/lmilbaum/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[+] Building 12.2s (14/16)                                 docker:desktop-linux
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 3.04kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.5s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 27.21kB         0.0s
 => [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com  0.0s
 => CACHED [dev_containers_target_stage 2/7] RUN mkdir -p /tmp/dev-contai  0.0s
 => CACHED [dev_containers_feature_content_normalize 2/3] COPY --from=dev  0.0s
 => CACHED [dev_containers_feature_content_normalize 3/3] RUN chmod -R 07  0.0s
 => CACHED [dev_containers_target_stage 3/7] COPY --from=dev_containers_f  0.0s
 => CACHED [dev_containers_target_stage 4/7] RUN echo "_CONTAINER_USER_HO  0.0s
 => ERROR [dev_containers_target_stage 5/7] RUN --mount=type=bind,from=d  11.5s
------                                                                          
 > [dev_containers_target_stage 5/7] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=ko_0,target=/tmp/build-features-src/ko_0     cp -ar /tmp/build-features-src/ko_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/ko_0  && cd /tmp/dev-container-features/ko_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/ko_0:
0.084 ===========================================================================
0.084 Feature       : ko (via Github Releases)
0.084 Description   : ko is a simple, fast container image builder for Go applications.
0.084 Id            : ghcr.io/devcontainers-contrib/features/ko
0.084 Version       : 1.0.9
0.084 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/ko
0.084 Options       :
0.084     VERSION="0.15.2"
0.084 ===========================================================================
1.971 nanolayer
6.439 cd /tmp/tmpguz3w_qo && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" REPO="ko-build/ko" BINARYNAMES="ko" VERSION="0.15.2" ASSETREGEX="" RELEASETAGREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" ADDITIONALFLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-wGJApCF2Bs/nanolayer" bash  -i  +H ./install.sh
6.439 Found a pre-existing nanolayer which were given in env variable: /tmp/nanolayer-wGJApCF2Bs/nanolayer
6.577 skipping usage of pre-existing nanolayer. (required version v0.5.4 does not match existing version 0.5.4)
9.618 nanolayer
11.17 'checksums.txt' filtered by '(\.sig$|\.text$|\.txt$|[Cc]hecksums|sha256|\.sha1$|\.md5$)' (negative)
11.17 'ko_0.15.2_Darwin_arm64.tar.gz' filtered by '([Mm]ac[Oo][Ss]|[Mm]ac\-[Oo][Ss]|\-osx\-|_osx_|[Dd]arwin|\.dmg)' (negative)
11.17 'ko_0.15.2_Darwin_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'ko_0.15.2_Linux_i386.tar.gz' filtered by '(i386|\-386|_386)' (negative)
11.17 'ko_0.15.2_Linux_ppc64le.tar.gz' filtered by '(\-ppc|ppc64|PPC64|_ppc)' (negative)
11.17 'ko_0.15.2_Linux_s390x.tar.gz' filtered by '(s390x|s390)' (negative)
11.17 'ko_0.15.2_Linux_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'ko_0.15.2_Windows_arm64.tar.gz' filtered by '(windows|Windows|WINDOWS|win32|\-win\-|\.msi$|.msixbundle$|\.exe$)' (negative)
11.17 'ko_0.15.2_Windows_i386.tar.gz' filtered by '(i386|\-386|_386)' (negative)
11.17 'ko_0.15.2_Windows_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'ko_Darwin_arm64.tar.gz' filtered by '([Mm]ac[Oo][Ss]|[Mm]ac\-[Oo][Ss]|\-osx\-|_osx_|[Dd]arwin|\.dmg)' (negative)
11.17 'ko_Darwin_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'ko_Linux_i386.tar.gz' filtered by '(i386|\-386|_386)' (negative)
11.17 'ko_Linux_ppc64le.tar.gz' filtered by '(\-ppc|ppc64|PPC64|_ppc)' (negative)
11.17 'ko_Linux_s390x.tar.gz' filtered by '(s390x|s390)' (negative)
11.17 'ko_Linux_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'ko_Windows_arm64.tar.gz' filtered by '(windows|Windows|WINDOWS|win32|\-win\-|\.msi$|.msixbundle$|\.exe$)' (negative)
11.17 'ko_Windows_i386.tar.gz' filtered by '(i386|\-386|_386)' (negative)
11.17 'ko_Windows_x86_64.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' (negative)
11.17 'multiple.intoto.jsonl' filtered by '.*ko.*' 
11.17 'ko_0.15.2_Linux_mips64le.tar.gz' filtered by '([Aa]rm64|ARM64)' 
11.17 'ko_0.15.2_Linux_riscv64.tar.gz' filtered by '([Aa]rm64|ARM64)' 
11.17 'ko_Linux_mips64le.tar.gz' filtered by '([Aa]rm64|ARM64)' 
11.17 'ko_Linux_riscv64.tar.gz' filtered by '([Aa]rm64|ARM64)' 
11.17 'ko_0.15.2_Linux_arm64.tar.gz' filtered by '(?i)(ubuntu)' 
11.17 'ko_Linux_arm64.tar.gz' filtered by '(?i)(ubuntu)' 
11.17 'ko_0.15.2_Linux_arm64.tar.gz' filtered by '.*static.*' 
11.17 'ko_Linux_arm64.tar.gz' filtered by '.*static.*' 
11.17 'ko_0.15.2_Linux_arm64.tar.gz' filtered by '(?i)(debian)' 
11.17 'ko_Linux_arm64.tar.gz' filtered by '(?i)(debian)' 
11.17 'ko_0.15.2_Linux_arm64.tar.gz' filtered by '\-ARM\-?|\-arm\-' 
11.17 'ko_Linux_arm64.tar.gz' filtered by '\-ARM\-?|\-arm\-' 
11.22 Traceback (most recent call last):
11.22   File "<string>", line 1, in <module>
11.22   File "nanolayer.__main__", line 50, in main
11.22   File "typer.main", line 328, in __call__
11.22   File "typer.main", line 311, in __call__
11.22   File "click.core", line 1157, in __call__
11.22   File "typer.core", line 778, in main
11.22   File "typer.core", line 216, in _main
11.22   File "click.core", line 1688, in invoke
11.22   File "click.core", line 1688, in invoke
11.22   File "click.core", line 1434, in invoke
11.22   File "click.core", line 783, in invoke
11.22   File "typer.main", line 683, in wrapper
11.22   File "nanolayer.cli.install", line 156, in install_gh_release_binary
11.22   File "nanolayer.installers.gh_release.gh_release_installer", line 145, in install
11.22   File "nanolayer.installers.gh_release.resolvers.asset_resolver", line 327, in resolve
11.22 nanolayer.installers.gh_release.resolvers.asset_resolver.AssetResolver.AssetResolverError: Too many matches found: ['ko_0.15.2_Linux_arm64.tar.gz', 'ko_Linux_arm64.tar.gz']
11.40 Traceback (most recent call last):
11.40   File "<string>", line 1, in <module>
11.40   File "nanolayer.__main__", line 50, in main
11.40   File "typer.main", line 328, in __call__
11.40   File "typer.main", line 311, in __call__
11.40   File "click.core", line 1157, in __call__
11.40   File "typer.core", line 778, in main
11.40   File "typer.core", line 216, in _main
11.40   File "click.core", line 1688, in invoke
11.40   File "click.core", line 1688, in invoke
11.40   File "click.core", line 1434, in invoke
11.40   File "click.core", line 783, in invoke
11.40   File "typer.main", line 683, in wrapper
11.40   File "nanolayer.cli.install", line 66, in install_devcontainer_feature
11.40   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
11.40   File "nanolayer.utils.invoker", line 59, in invoke
11.40 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpguz3w_qo && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" REPO="ko-build/ko" BINARYNAMES="ko" VERSION="0.15.2" ASSETREGEX="" RELEASETAGREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" ADDITIONALFLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-wGJApCF2Bs/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
11.52 ERROR: Feature "ko (via Github Releases)" (ghcr.io/devcontainers-contrib/features/ko) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/ko for help troubleshooting this error.
------
Dockerfile.extended:24
--------------------
  23 |     
  24 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=ko_0,target=/tmp/build-features-src/ko_0 \
  25 | >>>     cp -ar /tmp/build-features-src/ko_0 /tmp/dev-container-features \
  26 | >>>  && chmod -R 0755 /tmp/dev-container-features/ko_0 \
  27 | >>>  && cd /tmp/dev-container-features/ko_0 \
  28 | >>>  && chmod +x ./devcontainer-features-install.sh \
  29 | >>>  && ./devcontainer-features-install.sh \
  30 | >>>  && rm -rf /tmp/dev-container-features/ko_0
  31 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/ko_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/ko_0  && cd /tmp/dev-container-features/ko_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/ko_0" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/djrsd5kmxbyd789jp54xl6cpm
[17725 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/r6/rtdzvsy54cxcxql560gv7q840000gn/T/devcontainercli/container-features/0.56.2-1710017377179 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-pipeline-838924657317ed7625495b4f5866ac92012a218a3d2f3cdfd552017e701de02b-features -f /var/folders/r6/rtdzvsy54cxcxql560gv7q840000gn/T/devcontainercli/container-features/0.56.2-1710017377179/Dockerfile.extended /Users/lmilbaum/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[17725 ms]     at atA (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1260)
[17725 ms]     at yH (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1002)
[17725 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[17726 ms]     at async StA (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:3660)
[17726 ms]     at async ZC (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:4775)
[17726 ms]     at async trA (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11269)
[17726 ms]     at async erA (/Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11010)
[17734 ms] Exit code 1
[17736 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/lmilbaum/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-3a8dcda8-acc9-4cf4-acf7-b28c3d665db31710017376034 --workspace-folder /Users/lmilbaum/repos/github.com/lmilbaum/pipeline --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline --id-label devcontainer.config_file=/Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/lmilbaum/repos/github.com/lmilbaum/pipeline/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[17737 ms] Exit code 1
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features
