### ISSUE TITLE
[Bug]: pipx-package does not work with Alpine base

### ISSUE THREAD

**Issue by symplrdudley** [devcontainers-contrib/features#593]
### Feature id and version

ghcr.io/devcontainers-contrib/features/pipx-package:1.1.7

### Devcontainer base Image

docker.io/library/alpine:latest

### What happened?

when attempting to build an image with Alpine as the base and using these features, the pipx-package fails because it is only written for Ubuntu commands.

Then when using in Ubuntu I receive the following error:

```bash
root@3f30f6e23e6a:/workspaces/innovation-ansible-sre-datadog# ansible --version
ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
```

![image](https://github.com/devcontainers-contrib/features/assets/130775229/48bc526f-07d4-409e-9570-d8178f5d05c5)

```json
{
	"name": "SreAnsible",
    "image": "docker.io/library/alpine:latest",
	"customizations": {
		"vscode": {
			"extensions": [
 				"ms-azuretools.vscode-docker",
				"hashicorp.terraform",
				"ms-python.python",
				"ms-python.debugpy",
				"ms-python.vscode-pylance",
				"redhat.vscode-yaml",
				"DavidAnson.vscode-markdownlint",
				"ms-vscode.makefile-tools"
			]
		}
	},
	"features": {
		"ghcr.io/devcontainers/features/aws-cli:1": {},
		"ghcr.io/devcontainers/features/azure-cli:1": {},
		"ghcr.io/devcontainers-contrib/features/ansible:2": {},
		"ghcr.io/hspaans/devcontainer-features/ansible-lint:1": {},
		"ghcr.io/devcontainers/features/git:1": {}
	}
}
```

### Relevant log output

```shell
[21 ms] Dev Containers 0.354.0 in VS Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39).
[21 ms] Start: Run: wsl -d fedoraremix -e wslpath -u \\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog
[81 ms] Initializing configuration support...
[81 ms] Internal initialization of dev container support package...
[433 ms] Start: Resolving Remote
[435 ms] Start: Run: wsl -d fedoraremix -e wslpath -u \\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog
[830 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/pdudley/development/innovation-ansible-sre-datadog' && /bin/sh
[845 ms] Start: Run in host: id -un
[1164 ms] pdudley
[1164 ms] 
[1165 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'pdudley' || grep -E '^pdudley|^[^:]*:[^:]*:pdudley:' /etc/passwd || true)
[1169 ms] Start: Run in host: echo ~
[1173 ms] /home/pdudley
[1173 ms] 
[1173 ms] Start: Run in host: test -x '/home/pdudley/.vscode-remote-containers/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node'
[1176 ms] 
[1176 ms] 
[1176 ms] Exit code 1
[1177 ms] Start: Run in host: test -x '/home/pdudley/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node'
[1179 ms] 
[1179 ms] 
[1180 ms] Start: Run in host: test -f '/home/pdudley/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node_modules/node-pty/package.json'
[1181 ms] 
[1182 ms] 
[1182 ms] Start: Run in host: test -f '/home/pdudley/.vscode-remote-containers/dist/vscode-remote-containers-server-0.354.0.js'
[1184 ms] 
[1184 ms] 
[1185 ms] userEnvProbe: loginInteractiveShell (default)
[1185 ms] userEnvProbe: not found in cache
[1185 ms] userEnvProbe shell: /usr/bin/zsh
[1808 ms] userEnvProbe PATHs:
Probe:     '/home/pdudley/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/SqlCmd/:/mnt/c/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/whkd/bin/:/mnt/c/Program Files/komorebi/bin/:/mnt/c/PSTools:/mnt/c/Program Files/7-Zip:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Users/pdudley/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/pdudley/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/pdudley/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/pdudley/AppData/Local/Programs/Neovim/bin:/mnt/c/Users/pdudley/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/pdudley/AppData/Local/Pandoc/:/mnt/c/Users/pdudley/AppData/Local/Microsoft/WinGet/Packages/Microsoft.NuGet_Microsoft.Winget.Source_8wekyb3d8bbwe:/mnt/c/Users/pdudley/AppData/Roaming/npm:/mnt/c/Users/pdudley/AppData/Local/Microsoft/WinGet/Packages/Microsoft.Sysinternals.ProcessExplorer_Microsoft.Winget.Source_8wekyb3d8bbwe:/home/pdudley/.dotnet/tools'
Container: None
[1809 ms] Setting up container for folder or workspace: /home/pdudley/development/innovation-ansible-sre-datadog
[1824 ms] Start: Check Docker is running
[1824 ms] Start: Run in Host: docker version
[1830 ms] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

[2564 ms] Client:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.21.1
Built:        Tue Oct 31 09:32:01 2023
OS/Arch:      linux/amd64
[2568 ms] Start: Run in Host: docker volume ls -q
[3253 ms] Start: Run in Host: docker volume create vscode
[4337 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --filter label=vsch.quality=stable
[5559 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --filter label=devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json
[6672 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog
[7683 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog
[8998 ms] Running Dev Containers CLI:   read-configuration --workspace-folder /home/pdudley/development/innovation-ansible-sre-datadog --id-label devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --id-label devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --mount-workspace-git-root
[9008 ms] Start: Run in Host: /home/pdudley/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node /home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/pdudley/development/innovation-ansible-sre-datadog --id-label devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --id-label devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --mount-workspace-git-root
[9170 ms] @devcontainers/cli 0.58.0. Node.js v18.18.2. linux 5.15.146.1-microsoft-standard-WSL2 x64.
[9170 ms] Start: Run: git rev-parse --show-cdup
[9177 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --filter label=devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json
[10295 ms] Running Dev Containers CLI:   up --container-session-data-folder /tmp/devcontainers-2b22eb3b-2f8f-4669-b265-a560916493b11712952844907 --workspace-folder /home/pdudley/development/innovation-ansible-sre-datadog --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --id-label devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-f22120bb-79d9-4b2a-9397-e070ac7cfe5a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[10297 ms] Start: Run in Host: /home/pdudley/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node /home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-2b22eb3b-2f8f-4669-b265-a560916493b11712952844907 --workspace-folder /home/pdudley/development/innovation-ansible-sre-datadog --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --id-label devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-f22120bb-79d9-4b2a-9397-e070ac7cfe5a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[10458 ms] @devcontainers/cli 0.58.0. Node.js v18.18.2. linux 5.15.146.1-microsoft-standard-WSL2 x64.
[10458 ms] Start: Run: docker buildx version
[12845 ms] buildah 1.32.0
[12845 ms] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

[12845 ms] Start: Resolving Remote
[12848 ms] Start: Run: git rev-parse --show-cdup
[12853 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --filter label=devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json
[14095 ms] Start: Run: docker inspect --type image docker.io/library/alpine:latest
[15116 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/aws-cli:1'...
[15117 ms] * Processing feature: ghcr.io/devcontainers/features/aws-cli:1
[15476 ms] Start: Run: docker-credential-secret get
[15998 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[16181 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/azure-cli:1'...
[16181 ms] * Processing feature: ghcr.io/devcontainers/features/azure-cli:1
[16361 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[16543 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers-contrib/features/ansible:2'...
[16543 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/ansible:2
[16716 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/pipx-package
[16885 ms] * Processing feature: ghcr.io/devcontainers/features/python
[17068 ms] Resolving Feature dependencies for 'ghcr.io/hspaans/devcontainer-features/ansible-lint:1'...
[17068 ms] * Processing feature: ghcr.io/hspaans/devcontainer-features/ansible-lint:1
[17242 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/pipx-package
[17417 ms] * Processing feature: ghcr.io/devcontainers/features/python
[17592 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/ansible
[17769 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/git:1'...
[17769 ms] * Processing feature: ghcr.io/devcontainers/features/git:1
[17941 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[18152 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers/features/python' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers-contrib/features/pipx-package' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers/features/python' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers-contrib/features/pipx-package' is not required.  Removing from installation order...
[18153 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[18153 ms] * Fetching feature: ansible_0_oci
[18364 ms] * Fetched feature: ansible_0_oci version 2.0.17
[18364 ms] * Fetching feature: aws-cli_1_oci
[18562 ms] * Fetched feature: aws-cli_1_oci version 1.0.7
[18562 ms] * Fetching feature: azure-cli_2_oci
[18783 ms] * Fetched feature: azure-cli_2_oci version 1.2.3
[18784 ms] * Fetching feature: git_3_oci
[18966 ms] * Fetched feature: git_3_oci version 1.2.0
[18967 ms] * Fetching feature: ansible-lint_4_oci
[19189 ms] * Fetched feature: ansible-lint_4_oci version 1.0.2
[19203 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-pdudley/container-features/0.58.0-1712952860534 --build-arg _DEV_CONTAINERS_BASE_IMAGE=docker.io/library/alpine:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-innovation-ansible-sre-datadog-6c3cb4bfffaac0d0404821b72ed2f199104ba09b19c169672977859e09d53fa9-features -f /tmp/devcontainercli-pdudley/container-features/0.58.0-1712952860534/Dockerfile.extended /tmp/devcontainercli-pdudley/empty-folder
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[1/2] STEP 1/4: FROM docker.io/library/alpine:latest AS dev_containers_feature_content_normalize
[1/2] STEP 2/4: USER root
--> 37e706e1ba78
[1/2] STEP 3/4: COPY --from=dev_containers_feature_content_source devcontainer-features.builtin.env /tmp/build-features/
--> 3595fa579a18
[1/2] STEP 4/4: RUN chmod -R 0755 /tmp/build-features/
--> dfd25097185b
[2/2] STEP 1/13: FROM docker.io/library/alpine:latest AS dev_containers_target_stage
[2/2] STEP 2/13: USER root
--> Using cache 37e706e1ba78c789eb770ef1a17da55c3fea4a6e0c74b20ddfe5b9eada0c7c3e
--> 37e706e1ba78
[2/2] STEP 3/13: RUN mkdir -p /tmp/dev-container-features
--> 95d61895977b
[2/2] STEP 4/13: COPY --from=dev_containers_feature_content_normalize /tmp/build-features/ /tmp/dev-container-features
--> 89f0312eb6bf
[2/2] STEP 5/13: RUN echo "_CONTAINER_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env && echo "_REMOTE_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env
--> ed1ab2cde9c1
[2/2] STEP 6/13: RUN --mount=type=bind,from=dev_containers_feature_content_source,source=ansible_0,target=/tmp/build-features-src/ansible_0,z     cp -ar /tmp/build-features-src/ansible_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/ansible_0  && cd /tmp/dev-container-features/ansible_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/ansible_0
===========================================================================
Feature       : Ansible (via pipx)
Description   : Ansible is a suite of software tools that enables infrastructure as code.
Id            : ghcr.io/devcontainers-contrib/features/ansible
Version       : 2.0.17
Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/ansible
Options       :
    VERSION="latest"
===========================================================================
nanolayer
cd /tmp/tmpqcc3iteh && chmod +x -R . && _REMOTE_USER="root" _REMOTE_USER_HOME="/root" PACKAGE="ansible-core" INJECTIONS="ansible" VERSION="latest" INCLUDEDEPS="false" INTERPRETER="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-XXXXMpfjke/nanolayer" bash  -i  +H ./install.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nanolayer.__main__", line 50, in main
  File "typer.main", line 328, in __call__
  File "typer.main", line 311, in __call__
  File "click.core", line 1157, in __call__
  File "typer.core", line 778, in main
  File "typer.core", line 216, in _main
  File "click.core", line 1688, in invoke
  File "click.core", line 1688, in invoke
  File "click.core", line 1434, in invoke
  File "click.core", line 783, in invoke
  File "typer.main", line 683, in wrapper
  File "nanolayer.cli.install", line 65, in install_devcontainer_feature
  File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 131, in install
  File "nanolayer.utils.invoker", line 48, in invoke
  File "invoke", line 48, in run
  File "invoke.context", line 91, in run
  File "invoke.context", line 98, in _run
  File "invoke.runners", line 376, in run
  File "invoke.runners", line 421, in _run_body
  File "invoke.runners", line 1278, in start
FileNotFoundError: [Errno 2] No such file or directory: '/bin/bash'
cd /tmp/tmpqcc3iteh && chmod +x -R . && _REMOTE_USER="root" _REMOTE_USER_HOME="/root" PACKAGE="ansible-core" INJECTIONS="ansible" VERSION="latest" INCLUDEDEPS="false" INTERPRETER="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-XXXXMpfjke/nanolayer" bash  -i  +H ./install.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nanolayer.__main__", line 50, in main
  File "typer.main", line 328, in __call__
  File "typer.main", line 311, in __call__
  File "click.core", line 1157, in __call__
  File "typer.core", line 778, in main
  File "typer.core", line 216, in _main
  File "click.core", line 1688, in invoke
  File "click.core", line 1688, in invoke
  File "click.core", line 1434, in invoke
  File "click.core", line 783, in invoke
  File "typer.main", line 683, in wrapper
  File "nanolayer.cli.install", line 65, in install_devcontainer_feature
  File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 131, in install
  File "nanolayer.utils.invoker", line 59, in invoke
nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpqcc3iteh && chmod +x -R . && _REMOTE_USER="root" _REMOTE_USER_HOME="/root" PACKAGE="ansible-core" INJECTIONS="ansible" VERSION="latest" INCLUDEDEPS="false" INTERPRETER="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-XXXXMpfjke/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
ERROR: Feature "Ansible (via pipx)" (ghcr.io/devcontainers-contrib/features/ansible) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/ansible for help troubleshooting this error.
Error: building at STEP "RUN --mount=type=bind,from=dev_containers_feature_content_source,source=ansible_0,target=/tmp/build-features-src/ansible_0,z cp -ar /tmp/build-features-src/ansible_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/ansible_0  && cd /tmp/dev-container-features/ansible_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/ansible_0": while running runtime: exit status 1
[27537 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-pdudley/container-features/0.58.0-1712952860534 --build-arg _DEV_CONTAINERS_BASE_IMAGE=docker.io/library/alpine:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-innovation-ansible-sre-datadog-6c3cb4bfffaac0d0404821b72ed2f199104ba09b19c169672977859e09d53fa9-features -f /tmp/devcontainercli-pdudley/container-features/0.58.0-1712952860534/Dockerfile.extended /tmp/devcontainercli-pdudley/empty-folder
[27537 ms]     at htA (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:1260)
[27537 ms]     at kH (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:1002)
[27537 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[27537 ms]     at async UtA (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:3692)
[27537 ms]     at async $C (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[27537 ms]     at async QrA (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:13255)
[27537 ms]     at async urA (/home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:12996)
[27541 ms] Exit code 1
[27548 ms] Command failed: /home/pdudley/.vscode-server/bin/e170252f762678dec6ca2cc69aba1570769a5d39/node /home/pdudley/.vscode-remote-containers/dist/dev-containers-cli-0.354.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-2b22eb3b-2f8f-4669-b265-a560916493b11712952844907 --workspace-folder /home/pdudley/development/innovation-ansible-sre-datadog --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\fedoraremix\home\pdudley\development\innovation-ansible-sre-datadog --id-label devcontainer.config_file=/home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pdudley/development/innovation-ansible-sre-datadog/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-f22120bb-79d9-4b2a-9397-e070ac7cfe5a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[27548 ms] Exit code 1
```

**Comment by vanduc2514** [comment]
This issue happens also to me, and it happens because `ansbile` features will try to install `python` features first (from [this line](https://github.com/devcontainers-contrib/features/blob/main/src/ansible/devcontainer-feature.json#L19)). Python features will most likely to break on Alpine distro, even with latest version (3.19). Fix for me is to use another base development image from `mcr.io` 

```json
{
     "image": "mcr.microsoft.com/devcontainers/base:bullseye"
}
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned https://github.com/devcontainers-contrib/features/issues/628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451. There is a fork that is being worked on to update and maintain the features https://github.com/devcontainers-extra/features

**Comment by symplrdudley** [comment]
> This project is not associated with the devcontainer project and appears to have been abandoned #628 .

That's unfortunate. I'll have to open/copy this request on the new forked repository.
