### ISSUE TITLE
[Bug]: mkdocs installation of configured plugins crashes

### ISSUE THREAD

**Issue by JakobFerdinand** [devcontainers-contrib/features#623]
### Feature id and version

ghcr.io/devcontainers-contrib/features/mkdocs:2

### Devcontainer base Image

mcr.microsoft.com/devcontainers/universal:2

### What happened?

When I used to use the `mkdocs` feature with the `plugins` property set like this:
```json
{
	"image": "mcr.microsoft.com/devcontainers/universal:2",
	"features": {
		"ghcr.io/devcontainers-contrib/features/mkdocs:2": {
			"plugins": "mkdocs-material mkdocs-awesome-pages-plugin mkdocs-minify-plugin"
		}
	}
}
```
Since today, when I want to build my devcontainer `pipx` crashes when trying to install the plugins.
Log in the `Relevant log output` section.

The only way I found to do not run into that problem is by setting the `plugins` property to an empty string and install all plugins in the `postCreateCommand`.
```json
{
	"image": "mcr.microsoft.com/devcontainers/universal:2",
	"features": {
		"ghcr.io/devcontainers-contrib/features/mkdocs:2": {
			"plugins": ""
		}
	},
	"postCreateCommand": "pip3 install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-minify-plugin"
}
```

### Relevant log output

```shell
#15 0.455 ===========================================================================
#15 0.455 Feature       : MkDocs (via pipx)
#15 0.455 Description   : MkDocs is a fast, simple and downright gorgeous static site generator that's geared towards building project documentation.
#15 0.455 Id            : ghcr.io/devcontainers-contrib/features/mkdocs
#15 0.455 Version       : 2.0.18
#15 0.455 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/mkdocs
#15 0.455 Options       :
#15 0.455     VERSION="latest"
#15 0.455     PLUGINS="mkdocs-material mkdocs-awesome-pages-plugin mkdocs-minify-plugin"
#15 0.455 ===========================================================================
#15 1.240 nanolayer
#15 4.761 cd /tmp/tmpkxh3b445 && chmod +x -R . && _REMOTE_USER="codespace" _REMOTE_USER_HOME="/home/codespace" PACKAGE="mkdocs" INJECTIONS="mkdocs-material mkdocs-awesome-pages-plugin mkdocs-minify-plugin" VERSION="latest" INCLUDEDEPS="false" INTERPRETER="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-Ys0gf1z8nV/nanolayer" bash  -i  +H ./install.sh
  installed package mkdocs 1.6.0, installed using Python 3.10.13
#15 8.462   These apps are now globally available
#15 8.462     - mkdocs
#15 8.465 done! ✨ 🌟 ✨
#15 8.465 usage: pipx [-h] [--quiet] [--verbose] [--global] [--version]
#15 8.616             {install,install-all,uninject,inject,pin,unpin,upgrade,upgrade-all,upgrade-shared,uninstall,uninstall-all,reinstall,reinstall-all,list,interpreter,run,runpip,ensurepath,environment,completions}
#15 8.616             ...
#15 8.617 pipx: error: unrecognized arguments: mkdocs-material
#15 8.617 Traceback (most recent call last):
#15 8.667   File "<string>", line 1, in <module>
#15 8.667   File "nanolayer.__main__", line 50, in main
#15 8.668   File "typer.main", line 328, in __call__
#15 8.668   File "typer.main", line 311, in __call__
#15 8.668   File "click.core", line 1157, in __call__
#15 8.669   File "typer.core", line 778, in main
#15 8.669   File "typer.core", line 216, in _main
#15 8.670   File "click.core", line 1688, in invoke
#15 8.670   File "click.core", line 1688, in invoke
#15 8.670   File "click.core", line 1434, in invoke
#15 8.670   File "click.core", line 783, in invoke
#15 8.670   File "typer.main", line 683, in wrapper
#15 8.671   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#15 8.671   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 131, in install
#15 8.671   File "nanolayer.utils.invoker", line 59, in invoke
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned #628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451
