### ISSUE TITLE
[Bug]: age feature failed to build

### ISSUE THREAD

**Issue by hanson-andrew** [devcontainers-contrib/features#625]
### Feature id and version

ghcr.io/devcontainers-contrib/features/age:1

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:debian

### What happened?

Added the feature and rebuilt the container and got the error message.  It seems this is due to the most recent version of age published in their GitHub releases: https://github.com/FiloSottile/age/releases. Version 1.2.0 added additional assets with `*.proof` extensions.

If you downgrade the installation version from `latest` to `1.1.1` it installs just fine:
```
"ghcr.io/devcontainers-contrib/features/age:1": {
  "version": "1.1.1"
}

### Relevant log output

```shell
[2024-07-21T21:21:55.780Z]  > [dev_containers_target_stage  5/13] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=age_0,target=/tmp/build-features-src/age_0     cp -ar /tmp/build-features-src/age_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/age_0  && cd /tmp/dev-container-features/age_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/age_0:
[2024-07-21T21:21:55.780Z] 1.019 ===========================================================================
1.019 Feature       : age (via Github Releases)
[2024-07-21T21:21:55.781Z] 
1.019 Description   : age is a simple, modern and secure encryption tool (and Go library) with small explicit keys, no config options, and UNIX-style composability.
1.019 Id            : ghcr.io/devcontainers-contrib/features/age
1.019 Version       : 1.0.15
1.019 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/age
1.019 Options       :
1.019     VERSION="latest"
1.019 ===========================================================================
27.32 nanolayer
36.69 cd /tmp/tmp07v1xg0b && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" REPO="filosottile/age" BINARYNAMES="age" VERSION="latest" ASSETREGEX="" RELEASETAGREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" ADDITIONALFLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-meacOJO9hW/nanolayer" bash  -i  +H ./install.sh
36.69 Found a pre-existing nanolayer which were given in env variable: /tmp/nanolayer-meacOJO9hW/nanolayer

37.27 skipping usage of pre-existing nanolayer. (required version v0.5.4 does not match existing version 0.5.4)

56.10 nanolayer

[2024-07-21T21:21:55.781Z] 59.24 'age-v1.2.0-darwin-amd64.tar.gz' filtered by '([Mm]ac[Oo][Ss]|[Mm]ac\-[Oo][Ss]|\-osx\-|_osx_|[Dd]arwin|\.dmg)' (negative)

59.24 'age-v1.2.0-darwin-amd64.tar.gz.proof' filtered by '([Mm]ac[Oo][Ss]|[Mm]ac\-[Oo][Ss]|\-osx\-|_osx_|[Dd]arwin|\.dmg)' (negative)

59.24 'age-v1.2.0-darwin-arm64.tar.gz' filtered by '([Aa]rm64|ARM64)' (negative)

59.24 'age-v1.2.0-darwin-arm64.tar.gz.proof' filtered by '([Aa]rm64|ARM64)' (negative)

59.24 'age-v1.2.0-linux-arm64.tar.gz' filtered by '([Aa]rm64|ARM64)' (negative)

59.24 'age-v1.2.0-linux-arm64.tar.gz.proof' filtered by '([Aa]rm64|ARM64)' (negative)

[2024-07-21T21:21:55.781Z] 59.24 'age-v1.2.0-windows-amd64.zip' filtered by '(windows|Windows|WINDOWS|win32|\-win\-|\.msi$|.msixbundle$|\.exe$)' (negative)

[2024-07-21T21:21:55.781Z] 
59.24 'age-v1.2.0-windows-amd64.zip.proof' filtered by '(windows|Windows|WINDOWS|win32|\-win\-|\.msi$|.msixbundle$|\.exe$)' (negative)

59.25 'age-v1.2.0-linux-arm.tar.gz' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' 

59.25 'age-v1.2.0-linux-arm.tar.gz.proof' filtered by '([Aa]md64|\-x64|x64|x86[_-]64)' 

59.25 'age-v1.2.0-freebsd-amd64.tar.gz' filtered by '([Ll]inux)' 

59.25 'age-v1.2.0-freebsd-amd64.tar.gz.proof' filtered by '([Ll]inux)' 

59.25 'age-v1.2.0-linux-amd64.tar.gz' filtered by '(?i)(debian)' 

59.25 'age-v1.2.0-linux-amd64.tar.gz.proof' filtered by '(?i)(debian)' 

59.26 'age-v1.2.0-linux-amd64.tar.gz' filtered by '.*static.*' 

59.26 'age-v1.2.0-linux-amd64.tar.gz.proof' filtered by '.*static.*' 

59.26 'age-v1.2.0-linux-amd64.tar.gz' filtered by '(?i)(debian)' 

59.26 'age-v1.2.0-linux-amd64.tar.gz.proof' filtered by '(?i)(debian)' 

59.32 Traceback (most recent call last):

59.32   File "<string>", line 1, in <module>

59.32   File "nanolayer.__main__", line 50, in main

59.32   File "typer.main", line 328, in __call__

59.32   File "typer.main", line 311, in __call__

59.32   File "click.core", line 1157, in __call__

59.32   File "typer.core", line 778, in main

59.32   File "typer.core", line 216, in _main

59.32   File "click.core", line 1688, in invoke

59.32   File "click.core", line 1688, in invoke

59.32   File "click.core", line 1434, in invoke

59.32   File "click.core", line 783, in invoke

59.32   File "typer.main", line 683, in wrapper

59.33   File "nanolayer.cli.install", line 156, in install_gh_release_binary

59.33   File "nanolayer.installers.gh_release.gh_release_installer", line 145, in install

59.33   File "nanolayer.installers.gh_release.resolvers.asset_resolver", line 327, in resolve

59.33 nanolayer.installers.gh_release.resolvers.asset_resolver.AssetResolver.AssetResolverError: Too many matches found: ['age-v1.2.0-linux-amd64.tar.gz', 'age-v1.2.0-linux-amd64.tar.gz.proof']

[2024-07-21T21:21:55.781Z] 
60.22 Traceback (most recent call last):
60.22   File "<string>", line 1, in <module>
60.22   File "nanolayer.__main__", line 50, in main
60.22   File "typer.main", line 328, in __call__
60.22   File "typer.main", line 311, in __call__
60.22   File "click.core", line 1157, in __call__
60.22   File "typer.core", line 778, in main
60.22   File "typer.core", line 216, in _main
60.22   File "click.core", line 1688, in invoke
60.22   File "click.core", line 1688, in invoke
60.23   File "click.core", line 1434, in invoke
60.23   File "click.core", line 783, in invoke
60.23   File "typer.main", line 683, in wrapper
60.23   File "nanolayer.cli.install", line 66, in install_devcontainer_feature
60.23   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
60.23   File "nanolayer.utils.invoker", line 59, in invoke
60.23 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmp07v1xg0b && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" REPO="filosottile/age" BINARYNAMES="age" VERSION="latest" ASSETREGEX="" RELEASETAGREGEX="" BINLOCATION="/usr/local/bin" LIBNAME="" LIBLOCATION="/usr/local/lib" ADDITIONALFLAGS="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-meacOJO9hW/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
60.81 ERROR: Feature "age (via Github Releases)" (ghcr.io/devcontainers-contrib/features/age) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/age for help troubleshooting this error.
------
[2024-07-21T21:21:55.793Z] Dockerfile.extended:24
--------------------
  23 |     
  24 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=age_0,target=/tmp/build-features-src/age_0 \
  25 | >>>     cp -ar /tmp/build-features-src/age_0 /tmp/dev-container-features \
  26 | >>>  && chmod -R 0755 /tmp/dev-container-features/age_0 \
  27 | >>>  && cd /tmp/dev-container-features/age_0 \
  28 | >>>  && chmod +x ./devcontainer-features-install.sh \
  29 | >>>  && ./devcontainer-features-install.sh \
  30 | >>>  && rm -rf /tmp/dev-container-features/age_0
  31 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/age_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/age_0  && cd /tmp/dev-container-features/age_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/age_0" did not complete successfully: exit code: 1
[2024-07-21T21:21:55.824Z] Stop (69191 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-ahanson/container-features/0.66.0-1721596830839 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-ahanson/container-features/0.66.0-1721596830839/Dockerfile.extended -t vsc-pikube-b14c4e75083d50e43c44c679ee71aa9abf056e2b1deb991801708a4784440e69-features /tmp/devcontainercli-ahanson/empty-folder
[2024-07-21T21:21:55.828Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-ahanson/container-features/0.66.0-1721596830839 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-ahanson/container-features/0.66.0-1721596830839/Dockerfile.extended -t vsc-pikube-b14c4e75083d50e43c44c679ee71aa9abf056e2b1deb991801708a4784440e69-features /tmp/devcontainercli-ahanson/empty-folder
[2024-07-21T21:21:55.828Z]     at ptA (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:465:1260)
[2024-07-21T21:21:55.829Z]     at NH (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:465:1002)
[2024-07-21T21:21:55.829Z]     at async KtA (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:482:3771)
[2024-07-21T21:21:55.829Z]     at async eB (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:482:4886)
[2024-07-21T21:21:55.829Z]     at async hrA (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:663:200)
[2024-07-21T21:21:55.829Z]     at async lrA (/home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js:662:13452)
[2024-07-21T21:21:55.848Z] Stop (88193 ms): Run in Host: /home/ahanson/.vscode-server/bin/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/node /home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-8c1d4e49-1f6a-4454-813e-015864a8e7501721596824353 --workspace-folder /home/ahanson/code/pikube --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ahanson\code\pikube --id-label devcontainer.config_file=/home/ahanson/code/pikube/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ahanson/code/pikube/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-baa72dca-0ddb-4b5a-8bf2-e947d4d32e33.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-07-21T21:21:55.848Z] Exit code 1
[2024-07-21T21:21:55.863Z] Command failed: /home/ahanson/.vscode-server/bin/ea1445cc7016315d0f5728f8e8b12a45dc0a7286/node /home/ahanson/.vscode-remote-containers/dist/dev-containers-cli-0.375.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-8c1d4e49-1f6a-4454-813e-015864a8e7501721596824353 --workspace-folder /home/ahanson/code/pikube --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ahanson\code\pikube --id-label devcontainer.config_file=/home/ahanson/code/pikube/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ahanson/code/pikube/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-baa72dca-0ddb-4b5a-8bf2-e947d4d32e33.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-07-21T21:21:55.863Z] Exit code 1
[2024-07-21T21:21:57.965Z] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ahanson\code\pikube
[2024-07-21T21:21:58.532Z] Stop (567 ms): Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ahanson\code\pikube
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned #628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451

**Comment by evilhamsterman** [comment]
This issue is resolved in the fork
