### ISSUE TITLE
[Bug]: elm-asdf fails to build

### ISSUE THREAD

**Issue by JakobFerdinand** [devcontainers-contrib/features#631]
### Feature id and version

ghcr.io/devcontainers-contrib/features/elm-asdf:2

### Devcontainer base Image

mcr.microsoft.com/devcontainers/base:ubuntu

### What happened?

Using that configuration produces the following error log when building the container.

```json
{
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    "features": {
	"ghcr.io/devcontainers-contrib/features/elm-asdf:2": {}
    }
}
```

My current workaround is to install elm manually like that:
```json
{
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    //"features": {
    //    "ghcr.io/devcontainers-contrib/features/elm-asdf:2": {}
    //},
    "postCreateCommand": "curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz && gunzip elm.gz && chmod +x elm && sudo mv elm /usr/local/bin/"
}
```

### Relevant log output

```shell
2024-08-12 09:30:08.146Z: #15 6.628 Plugin elm's list-all callback script failed with output:
2024-08-12 09:30:08.147Z: 
2024-08-12 09:30:08.266Z: #15 6.630 

2024-08-12 09:30:08.266Z: #15 6.631 

#15 6.650 elm  is already installed

#15 6.747 Plugin elm's list-all callback script failed with output:

2024-08-12 09:30:08.401Z: #15 6.749 

#15 6.751 
2024-08-12 09:30:08.401Z: 
#15 6.780 Traceback (most recent call last):
#15 6.780   File "<string>", line 1, in <module>
#15 6.780   File "nanolayer.__main__", line 50, in main
#15 6.781   File "typer.main", line 328, in __call__
#15 6.782   File "typer.main", line 311, in __call__
#15 6.782   File "click.core", line 1130, in __call__2024-08-12 09:30:08.401Z: 
#15 6.782   File "typer.core", line 778, in main
#15 6.783   File "typer.core", line 216, in _main
#15 6.783   File "click.core", line 1657, in invoke
#15 6.783   File "click.core", line 1657, in invoke
#15 6.783   File "click.core", line 1404, in invoke
#15 6.783   File "click.core", line 760, in invoke
#15 6.783   File "typer.main", line 683, in wrapper
#15 6.783   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
#15 6.784   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
#15 6.785   File "nanolayer.utils.invoker", line 56, in invoke
#15 6.785 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpcikxx_al && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" PLUGIN="elm" VERSION="latest" PLUGINREPO="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-9JsPpsunaJ/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.2024-08-12 09:30:08.401Z: 
#15 6.879 ERROR: Feature "Elm (via asdf)" (ghcr.io/devcontainers-contrib/features/elm-asdf) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/elm-asdf for help troubleshooting this error.
2024-08-12 09:30:08.522Z: #15 ERROR: process "/bin/sh -c cp -ar /tmp/build-features-src/elm-asdf_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/elm-asdf_0  && cd /tmp/dev-container-features/elm-asdf_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/elm-asdf_0" did not complete successfully: exit code: 12024-08-12 09:30:08.522Z: 
2024-08-12 09:30:08.734Z: ------
 > [dev_containers_target_stage 5/6] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=elm-asdf_0,target=/tmp/build-features-src/elm-asdf_0     cp -ar /tmp/build-features-src/elm-asdf_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/elm-asdf_0  && cd /tmp/dev-container-features/elm-asdf_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/elm-asdf_0:
6.783   File "click.core", line 1657, in invoke
6.783   File "click.core", line 1657, in invoke
6.783   File "click.core", line 1404, in invoke
6.783   File "click.core", line 760, in invoke
6.783   File "typer.main", line 683, in wrapper
6.783   File "nanolayer.cli.install", line 65, in install_devcontainer_feature
6.784   File "nanolayer.installers.devcontainer_feature.oci_feature_installer", line 134, in install
6.785   File "nanolayer.utils.invoker", line 56, in invoke
6.785 nanolayer.utils.invoker.Invoker.InvokerException: The command 'cd /tmp/tmpcikxx_al && chmod +x -R . && _REMOTE_USER="vscode" _REMOTE_USER_HOME="/home/vscode" PLUGIN="elm" VERSION="latest" PLUGINREPO="" NANOLAYER_VERBOSE="" NANOLAYER_FORCE_CLI_INSTALLATION="" NANOLAYER_PROPAGATE_CLI_LOCATION="1" NANOLAYER_CLI_LOCATION="/tmp/nanolayer-9JsPpsunaJ/nanolayer" bash  -i  +H ./install.sh' failed. error: Return Code: 1. see logs for details.
6.879 ERROR: Feature "Elm (via asdf)" (ghcr.io/devcontainers-contrib/features/elm-asdf) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/elm-asdf for help troubleshooting this error.
------
2024-08-12 09:30:08.734Z: Dockerfile.extended:24
--------------------
  23 |     
  24 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=elm-asdf_0,target=/tmp/build-features-src/elm-asdf_0 \
  25 | >>>     cp -ar /tmp/build-features-src/elm-asdf_0 /tmp/dev-container-features \
  26 | >>>  && chmod -R 0755 /tmp/dev-container-features/elm-asdf_0 \
  27 | >>>  && cd /tmp/dev-container-features/elm-asdf_0 \
  28 | >>>  && chmod +x ./devcontainer-features-install.sh \
  29 | >>>  && ./devcontainer-features-install.sh \
  30 | >>>  && rm -rf /tmp/dev-container-features/elm-asdf_0
  31 |     
--------------------
2024-08-12 09:30:08.734Z: ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/elm-asdf_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/elm-asdf_0  && cd /tmp/dev-container-features/elm-asdf_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/elm-asdf_0" did not complete successfully: exit code: 1
2024-08-12 09:30:08.739Z: Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1723454979093 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-jakobferdinand.at-07b9f950643cf9802ec6cf0623ed168949b9a9c3def65ad659ff7f2d6bd641ab-features -f /tmp/devcontainercli-root/container-features/0.56.1-1723454979093/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2024-08-12 09:30:08.739Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1723454979093 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-jakobferdinand.at-07b9f950643cf9802ec6cf0623ed168949b9a9c3def65ad659ff7f2d6bd641ab-features -f /tmp/devcontainercli-root/container-features/0.56.1-1723454979093/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
2024-08-12 09:30:08.740Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1723454979093 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-jakobferdinand.at-07b9f950643cf9802ec6cf0623ed168949b9a9c3def65ad659ff7f2d6bd641ab-features -f /tmp/devcontainercli-root/container-features/0.56.1-1723454979093/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2024-08-12 09:30:08.745Z:     at O$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:1253)
2024-08-12 09:30:08.746Z:     at iK (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:997)
2024-08-12 09:30:08.747Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-12 09:30:08.748Z:     at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3660)
2024-08-12 09:30:08.748Z:     at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
2024-08-12 09:30:08.749Z: devcontainer process exited with exit code 1
2024-08-12 09:30:08.749Z:     at async xeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11265)
2024-08-12 09:30:08.749Z:     at async UeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11006)

====================================== ERROR ====================================
2024-08-12 09:30:08.754Z: Failed to create container.
=================================================================================
2024-08-12 09:30:08.754Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.56.1-1723454979093 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-jakobferdinand.at-07b9f950643cf9802ec6cf0623ed168949b9a9c3def65ad659ff7f2d6bd641ab-features -f /tmp/devcontainercli-root/container-features/0.56.1-1723454979093/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2024-08-12 09:30:08.754Z: Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)

====================================== ERROR ====================================
2024-08-12 09:30:08.759Z: Container creation failed.
=================================================================================
```

**Comment by evilhamsterman** [comment]
This project is not associated with the devcontainer project and appears to have been abandoned #628 . The official project has removed all devcontainer-contrib features from their listing. https://github.com/devcontainers/devcontainers.github.io/issues/451
